### ISSUE TITLE
Perfsonar 3.5 configuration forces redirect to /toolkit/ for all virtual hosts

### ISSUE THREAD

**Issue by candlerb** [perfsonar/toolkit#103]
> This was first reported 2015-10-16 on [perfsonar-developer](https://lists.internet2.edu/sympa/arc/perfsonar-developer/2015-10/msg00117.html)

We are using IP-based virtual hosting to host an additional testing service on perfsonar boxes:

```
===> /etc/httpd/conf.d/speedtest.conf <===
<VirtualHost speedtest.example.com:*>
ServerName speedtest.example.com
DocumentRoot /var/www/speedtest.example.com
</VirtualHost>
```

When the box updated itself to 3.5, this broke. Accessing speedtest.example.com returned a redirect to /toolkit/ and hence the user saw perfsonar instead.

The problem is in `/etc/httpd/conf.d/toolkit_root_redirect.conf`

On a 3.4.2 box this said:

```
RewriteEngine on
RewriteCond %{HTTP_HOST} =""
RewriteRule ^/$ http://%{SERVER_ADDR}/toolkit/

RewriteCond %{HTTP_HOST} !=""
RewriteRule ^/$ http://%{HTTP_HOST}/toolkit/
```

However in 3.5 this has become a single line:

```
RedirectMatch ^/$ /toolkit/
```

Putting it back to how it was before makes it work again: access to the perfsonar hostname gets the redirect, but access to speedtest.example.com does not. (To be honest I don't understand exactly how those HTTP_HOST conditions actually solve the problem, but they do :-)

Then on 17th February 2016 the problem recurred; it looks like a software update has again overwritten `/toolkit_root_redirect.conf` with the new one. Again I had to replace it and restart apache.

I am looking for a permanent solution to this problem, so that future upgrades don't break this again.
## Analysis

This configuration comes from `scripts/system_environment/enable_apache_redirect` and it looks like this was changed in commit 72dbe4e 

I'd be just as happy using named virtual hosts instead of IP-based. I only used an IP-based virtualhost because I wanted to avoid making any changes to the perfsonar-installed apache config - and that was precisely so that it wouldn't be broken by upgrades. Unfortunately that turned out not to be the case :-( 

I believe the ideal long-term solution would be to wrap all the perfsonar configuration in a default virtualhost, rather than using top-level or "main server" configuration, so that other virtualhosts aren't tainted by the `/toolkit/` redirect (or indeed any other perfsonar configs)

I think you probably want a single `000_perfsonar.conf` which contains:

```
NameVirtualHost *:80
<VirtualHost *:80>
... put all toolkit and esmond config in here
</VirtualHost>
```

You don't want `<VirtualHost _default_:80>` because that only responds on IP addresses which don't have their own `NameVirtualHost` declaration, at least if I understand [the documentation](https://httpd.apache.org/docs/2.2/vhosts/examples.html) correctly.

This configuration probably needs duplicating for ssl unfortunately (but has the advantage that it should allow SNI to select other SSL virtualhosts on the same box)

I believe that doing the above will make perfsonar work the same as currently for normal users - that is, it will accept connections on any IP interface, and will serve perfsonar content for any hostname. However it allows other virtualhosts to be added which are independent from the perfsonar configuration.

**Comment by bltierney** [comment]
Andy: has this been addressed?

**Comment by arlake228** [comment]
After spending some time with this I think I was refreshed on why we do things the way we do. First of all, going back to the old method of the redirects I believe gives trouble on private hosts that don't have a fully qualified domain. It was also giving me some trouble in the virtual host that we know have to have for the new admin area that wasn't around in 3.4. At the end of the day, I don't think putting your own virtualhost directives on a toolkit node is a use case we want to support anyways. It seems like the main use case for this was providing an easier address to NDT, which we don't support anymore anyways. The main point of the toolkit node is that it's the only thing on the system and more or less has control of that system's config. If you want it to have less control, that is why we offer the other bundles like perfsonar-core and perfsonar-testpoint with add-on packages.
