### ISSUE TITLE
Option to configure toolkit firewall ssh rules

### ISSUE THREAD

**Issue by apertome** [perfsonar/toolkit#104]
Received the following request:

> I'd like to see the UI give you the ability to craft your ssh rules. By default you can have it open, but it should something to say "Please specify hosts or subnets for SSH access"

This would help in environments where wide open SSH access is not desirable.

**Comment by igarny** [comment]
I also would like to support Mark's opinion. IMHO pS is not about FW management.
Please check this: https://github.com/perfsonar/toolkit/issues/180

**Comment by mfeit-internet2** [comment]
We've had the debate on and off about whether or not installing a package should also set the firewall up so it will work.  I can argue both sides of it.

**Comment by apertome** [comment]
I tend to agree that I don't really think we need to be building sysadmin tools. 

Also, IIRC, this request came from headaches some people were having relating to the Toolkit overriding their iptables config. Now that we can run bundles rather than Toolkit nodes, this really isn't an issue any longer, in my view.

Closing.
