### ISSUE TITLE
perfsonar-configure_nic_parameters contains old services names

### ISSUE THREAD

**Issue by nuqleo** [perfsonar/toolkit#108]
bwctld and owampd services renamed to bwctl-server and owamp-server but /etc/init.d/perfsonar-configure_nic_parameters from perfsonar-toolkit-3.5.1-1.noarch contains old services names

OWAMP=`/sbin/chkconfig --list owampd | grep -w on`
BWCTL=`/sbin/chkconfig --list bwctld | grep -w on`

**Comment by tonin** [comment]
The code of this script has been completely removed in release 4.0 but this particular error had been corrected for 3.5.1.2 by commit https://github.com/perfsonar/toolkit/commit/4ccf0f4db219915c801e03d2373b92cca8517f99
