### ISSUE TITLE
Duplicate Tests created when using GUI

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#109]
From Amit Khare at Canarie:

> Our perfSONAR nodes were recently upgraded to the latest toolkit release, however we noticed an issue with the ‘Tests’  GUI.
> Every time we click save, a duplicate test is created for our mesh nodes.
> We were making changes to our latency node in Vancouver, now we have 5 duplicate tests, please see the snippet below.
> We were able to recreate the issue in other nodes as well. Thank you very much for looking into it. 

![unnamed](https://cloud.githubusercontent.com/assets/634851/13745553/12a3746c-e9c5-11e5-802e-1b16660c6b27.png)

**Comment by apertome** [comment]
Thanks for submitting this. I'm looking into it.

**Comment by apertome** [comment]
Reproduced in my dev environment and working on a fix and some other enhancements relating to auto-generated tests.

**Comment by apertome** [comment]
This has been resolved.

The GUI now shows an indicator for auto-generated tests (either generated by mesh config, or traceroute default tests) and prevents you from editing/deleting them.

For people who have duplicate tests showing up in their configuration, they can safely delete the duplicates. Once they get this update they will see that the duplicates are not recognized as autogenerated, and it will be easier to delete them.
