### ISSUE TITLE
Ability to specify multiple streams for bandwidth test in GUI

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#110]
Title says it all. This was requested at a perfSONAR workshop led by Jason Z. and John H.

**Comment by mfeit-internet2** [comment]
If we're going to do another dot release, this could be added to BWCTL in a few hours.

For pScheduler, it'll become part of the test spec and the tools will implement it.

**Comment by apertome** [comment]
I'm confused, I thought the request was to add this to the GUI. Does it need to be added to bwctl first?

**Comment by mfeit-internet2** [comment]
You were right, it's just the GUI.  I had it in my head that BWCTL didn't support that, but it does (`-P` switch).

**Comment by lisaens** [comment]
I've added a 'streams' field to the test config form.

**Comment by lisaens** [comment]
It's been merged into master as part of advanced-tab branch
