### ISSUE TITLE
perfsonar-configure_nic_parameters no longer setting txqueuelen

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#112]
From user:

It appears that txqueuelen is no longer being set appropriately via the perfsonar-configure_nic_parameters rc script. This script sets txqueuelen to 10000 if BWCTL is enabled. To find out if BWCTL is enabled it does the following: 

BWCTL=`/sbin/chkconfig --list bwctld | grep -w on` 

Which fails because bwctld is now bwctl-server and should be: 

BWCTL=`/sbin/chkconfig --list bwctl-server | grep -w on`

**Comment by tonin** [comment]
This had been corrected in 4ccf0f4d, closing.
