### ISSUE TITLE
Allow users to choose iperf/iperf3 test via GUI (also choose traceroute options)

### ISSUE THREAD

**Issue by sowmyab** [perfsonar/toolkit#113]
A user reported

"......after the upgrade to v3.5.1, a single CPU in the LIVA box hits 99.9% CPU utilization when I run bwctl tests manually. When I force the bwctl test to use iperf instead of iperf3 (adding "-T iperf” option to bwctl command), the performance goes back to normal (~900Mbps), and both CPUs are utilized. 

Is there a way to make the regular bandwidth tests to use iperf instead of iperf3 by default in perfSONAR v3.5.1?"

Currently, this is not possible via GUI and has to be done manually by editing the regulartesting.conf file. It will be valuable to add this option to GUI.

**Comment by apertome** [comment]
This should go under the "advanced" tab.

**Comment by lisaens** [comment]
I previously added a Tools selector to the advanced tab for throughput tests. It allows the user to add, remove, and drag to reorder iperf and iperf3.
Today, I moved the Tools selector for traceroute tests to the advanced tab and made it work like that for throughput tests. Users can choose and drag to reorder traceroute, tracepath, and paris-traceroute.

**Comment by lisaens** [comment]
This has been merged into master as part of the advanced-tab branch
