### ISSUE TITLE
update TCP tuning settings

### ISSUE THREAD

**Issue by bltierney** [perfsonar/toolkit#114]
The current settings are from about 4 years ago. Now that we have lots of 40G hosts, they should be updated to the settings described here:

https://fasterdata.es.net/host-tuning/linux/test-measurement-host-tuning/

We should also consider different settings for 40G vs 10G hosts.

**Comment by arlake228** [comment]
Assigning self to review if this is already done.

**Comment by bltierney** [comment]
The current settings are still fine for 10G hosts, but I think we should use different settings for 40G/100G hosts if possible.

**Comment by arlake228** [comment]
We already do this in the script: https://github.com/perfsonar/toolkit/blob/master/scripts/configure_sysctl

We detect interfaces greater than 40G and apply settings according to fasterdata. This was added as part of 4.0.
