### ISSUE TITLE
Add display of communities on the main Toolkit page

### ISSUE THREAD

**Issue by apertome** [perfsonar/toolkit#115]
Older versions of the Toolkit displayed a list of communities on the main Toolkit page. The current version does not. We should add this.

**Comment by lisaens** [comment]
Added a list of communities to the Host Details part of the sidebar.

**Comment by lisaens** [comment]
Changed the css so the Communities section is 1 column wide, rather than 2 columns.

**Comment by apertome** [comment]
Merged pull request. done.
