### ISSUE TITLE
NTP shows it is synced on toolkit page when it is not

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#116]
On the USATLAS throughput call it was reported by Marian that the main toolkit web page show NTP as synced even when it is not. They had a very clear case where the NTP hosts was not synced but the web page indicated it was.

**Comment by tonin** [comment]
Have we seen this appearing again?  Do we have a way to reproduce the behaviour?

**Comment by apertome** [comment]
I have not seen it at all, not sure how to reproduce, although I haven't tried much, either.

**Comment by arlake228** [comment]
Unable to reproduce and haven't heard anything for over 6 months. Closing.
