### ISSUE TITLE
Unable to add tests if LS cache files not on system

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#119]
Currently if someone tries to add a test but the lscachedaemon has not downloaded the tarball, the test configuration GUI will not respond when you click on the Add Test button. This is a problem for some hosts in isolated environment that can't hit perfsonar.net or the ESnet hosts to get the traball. It's relatively easy to recreate by deleting /var/lib/perfsonar/lscache and trying to use the Test Configuration GUI.

**Comment by arlake228** [comment]
Could we perhaps bump the priority of this? We've had to answer multiple questions related to this on the mailing list the past couple months. It's might even be worth releasing a small bugfix patch once we have it.

**Comment by apertome** [comment]
That's a good idea, thanks for bringing it to my attention again.

**Comment by apertome** [comment]
Added a fix for this in master, about to add it to the release-3.5.1 branch so we can release a bugfix soon

**Comment by apertome** [comment]
This has now been fixed in both master and the release branch.
