### ISSUE TITLE
Use ip instead of ifconfig in mod_interface_route

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#120]
We should update https://github.com/perfsonar/toolkit/blob/master/scripts/mod_interface_route to use ip instead of ifconfig. A similar change was made in perfsonar/ls-registration-daemon#18.

**Comment by vvidic** [comment]
On Wed, Apr 27, 2016 at 09:21:14AM -0700, Andrew R. Lake wrote:
> We should update
> https://github.com/perfsonar/toolkit/blob/master/scripts/mod_interface_route
> to use ip instead of ifconfig. A similar change was made in
> perfsonar/ls-registration-daemon#18.

The following are updated in the centos7 branch, please take a look:

* scripts/mod_interface_route
* init_scripts/perfsonar-configure_nic_parameters

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by vvidic** [comment]
I think all of these changes are merged so closing.
