### ISSUE TITLE
Add tcp tuning settings to host json

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#128]
Jason Z requested we add TCP tuning settings to the JSO at host.cgi?method=get_summary. We should do this.

**Comment by apertome** [comment]
We should also add this to the host details section of the UI

**Comment by apertome** [comment]
The backend change needs to happen in the perl-shared library:
https://github.com/perfsonar/perl-shared/blob/fda69c54c10df7c74c882a9dd1f546d4bd4f34d4/lib/perfSONAR_PS/NPToolkit/DataService/Host.pm#L348

You should be able to just uncomment that line and `$tcp_info` should contain the tcp tuning info. I'm not sure what that datastructure will look like exactly; most likely you can just set 

```
$status->{tcp_info} = $tcp_info;
````
You will need to check and make sure the data structure makes sense. I think it will be something like this (random numbers used for example):

```
{
        tcp_cc_algorithm => "value",
        tcp_max_buffer_send => 1234,
        tcp_max_buffer_recv => 4321,
        tcp_autotune_max_buffer_send => 9876,
        tcp_autotune_max_buffer_recv => 54321,
        tcp_max_backlog => 2468
}
```

If it looks different from this, you might need to do some manipulation (for instance, if it's all in an array we don't want that, etc)

Make sure the numeric fields are numeric (not strings).

If one or more of the values is `null` or `undefined` you can delete it from the hash; we only want the key if there is also a value.

These values should show up here:
http://perfsonar-dev9.grnoc.iu.edu/toolkit/services/host.cgi?method=get_details
and
http://perfsonar-dev9.grnoc.iu.edu/toolkit/services/host.cgi?method=get_summary

Note: `get_summary` is a  function that calls several other functions to get their data, one of which is `get_details`
