### ISSUE TITLE
Evaluate test definition strategy

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#13]
_From @arlake228 on March 14, 2015 12:18_

Original [issue 907](https://code.google.com/p/perfsonar-ps/issues/detail?id=907) created by arlake228 on 2014-06-04T17:37:44.000Z:

If doing a GUI re-work, we should evaluate how we define tests. Currently you define the test parameters first then the host pairs that run that test. Perhaps the right things to do is define the set of hosts first and then then tests you want run between them. This is a subtle but potentially important difference when designing GUIs and test configurations. 

_Copied from original issue: perfsonar/project#905_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=907#c1) originally posted by arlake228 on 2014-06-17T20:06:40.000Z:

Here's a mockup of what it might look like. I think this rework is more important wrt  Issue 933 since we're automatically adding hosts to a test that the user never requested.

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=907#c2) originally posted by arlake228 on 2015-01-27T15:21:16.000Z:

&lt;empty&gt;

**Comment by apertome** [comment]
Re-adding the image

![screen shot 2014-06-17 at 4 01 46 pm](https://cloud.githubusercontent.com/assets/6306575/6731634/908c7ec0-ce1c-11e4-8f1c-3c5510558d5d.png)

**Comment by apertome** [comment]
Aaron put together an example regular testing config:

http://ndb1.internet2.edu/~aaron/regular_testing.mockup.conf

**Comment by apertome** [comment]
This is underway and being tracked as part of the project planning. Don't need the ticket anymore.
