### ISSUE TITLE
Change the LS status displayed in the GUI to use the UUID

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#130]
As has been the case forever, the thing that displays the LS status is highly inconsistent with regards to its accuracy. It tries to lookup the host record using the hostname or IP and often gets it wrong. We should switch it to the host UUID since that will be much more consistent.

**Comment by igarny** [comment]
Hi Andy,
I would assume the UUID would be used for diagnosis of LS registration, right?
My suggestion is that UUID is kept under the authenticated access pages.

Regards,
Ivan

**Comment by arlake228** [comment]
The uuid will not be displayed, this is purely for the backend.



On July 4, 2016 at 5:24:21 AM, Ivan Garnizov (notifications@github.com)
wrote:

Hi Andy,
I would assume the UUID would be used for diagnosis of LS registration,
right?
My suggestion is that UUID is kept under the authenticated access pages.

Regards,
Ivan

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/perfsonar/toolkit/issues/130#issuecomment-230246034>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAmv41pHyTJ9OUROTInbrtMAbZop_vojks5qSNFDgaJpZM4I6qti>
.

**Comment by arlake228** [comment]
Fixed in perl-shared awhile back.
