### ISSUE TITLE
Toolkit error from bwctl/traceroute parsing

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/toolkit#133]
Hi,

Toolkit throws errors (and drawing red thick line in the graph) with messages like:
Error from bwctl/traceroute:
Problem parsing traceroute output: Unable to parse traceroute output: H 3000.233 ms !H 3000.204 ms !H at /usr/share/perl5/vendor_perl/Net/Traceroute.pm line 745.
16:18:43 07/06/2016
I guess it has troubles in parsing such traceroute outputs however it is still a valid traceroute.

**Comment by arlake228** [comment]
Deprecated in pScheduler. Closing
