### ISSUE TITLE
interface selection dialog improvement

### ISSUE THREAD

**Issue by igarny** [perfsonar/toolkit#134]
Dear pS dev,

![image](https://cloud.githubusercontent.com/assets/11942774/16765954/47c445c4-4837-11e6-853a-ae08185a6d96.png)

On the picture above you will see one of the difficulties admins have to deal with on hosts with multiple interfaces.
The problem refers to the inability to select the proper interface for any of the possible performance tests (in particular throughput).

The information for the test type assignments to local network interfaces is already available in the local file: /etc/perfsonar/lsregistrationdaemon.conf 
Best solution would be if magically the dialog is able to remove from the list interfaces, for which there are specific assignments with test types not related to current selection. 

It would be sufficient, though, to have a legend of the interfaces with their DNS records so that admins are able to easily determine the correct interface by naming or have DNS names in the list. This would at least help parties, which maintain a lean organization in DNS.

Regards,
Ivan

**Comment by apertome** [comment]
This would be a nice improvement, thanks for the suggestion.

**Comment by apertome** [comment]
Set this as 3.6 -- we may or may not be able to fit it in on that timeframe, but we'll try.

**Comment by apertome** [comment]
Lisa will be looking at this

**Comment by apertome** [comment]
To clarify, the portion we intend to implement is this:

> It would be sufficient, though, to have a legend of the interfaces with their DNS records so that admins are able to easily determine the correct interface by naming or have DNS names in the list. This would at least help parties, which maintain a lean organization in DNS.

**Comment by lisaens** [comment]
I've added a list of hostnames and/or IP addresses following the interface names in the dropdown (all the hostnames for the ipv4 and ipv6 addresses assigned to the interface, or the address if there's no name)
