### ISSUE TITLE
Add new metadata fields to GUI

### ISSUE THREAD

**Issue by apertome** [perfsonar/toolkit#137]
We need to add new metadata fields to the GUI (these are all auto-detected and we can get them from the LS):

- [ ] host-vm - Indicates whether or not the host is a VM

- [ ] host-manufacturer - Indicates the hardware or VM manufacturer

- [ ] host-productname - Indicates the model of the hardware or VM host

Example from http://ps-west.es.net:8090/lookup/host/2e7ca03d-e9e4-45f8-9e59-4a68bbdec5b7
```
{
-"host-vm": [
"0"
],
-"host-manufacturer": [
"ECS"
],
-"host-productname": [
"BAT-MINI"
]
}
```

If possible, we should see if there are any good  Font Awesome icons we can use to represent these.

**Comment by tonin** [comment]
Would this be added to the public or private GUI page?

Maybe we can add `host-os-name` and `host-os-version` too?

**Comment by apertome** [comment]
I was thinking it would be public, but I'm open to suggestions. Adding OS name/version seems like a good idea, too. Do you think this information should be public or private?

**Comment by tonin** [comment]
I too think it can be public.

**Comment by mfeit-internet2** [comment]
It would certainly be one more thing the DEFCON guy could us in enumerating his targets.  :-)

**Comment by tonin** [comment]
Yes, but this information is public already as posted to the LS.

**Comment by apertome** [comment]
Exactly.

**Comment by apertome** [comment]
Lisa will be handling this one.

**Comment by lisaens** [comment]
Done!
