### ISSUE TITLE
Prepare for pScheduler integration

### ISSUE THREAD

**Issue by apertome** [perfsonar/toolkit#139]
In preparation for integrating pscheduler, we'll need some more unit tests for the test config section. I will work with Lisa to get these in place. We may find other tasks that need to be addressed as well.

**Comment by lisaens** [comment]
~8/30 = I  added tests for get_test_configuration and delete_all_tests functions:  t/test-get_tests.t, t/test-delete_all_tests.t , and accompanying files  t/expected/test-get_tests.txt and t/etc/regulartesting.conf. 
These have been pushed to unit-tests branch.

~9/2 - I also added some things to the prototype UI on the master branch.
