### ISSUE TITLE
Enabling wheel group sudo might prevent users to sudo

### ISSUE THREAD

**Issue by tonin** [perfsonar/toolkit#146]
In a recent deployment I was given administration rights on a machine through a user which was part of the `wheel` group but had a special sudo rule setup that enabled this user to sudo without password.  The sudoers.d/file for this user was:

`user ALL=(ALL) NOPASSWD:ALL`

When the toolkit added the

`%wheel        ALL=(ALL)       ALL`

config to /etc/sudoers this user was denied sudo rights (and no password was set for this user, actually rendering the admin access to the machine impossible).

Is this wheel sudo rule mandatory for all toolkit installations?  I think that in the case of bundles installation, we shouldn't do automatic configuration of sensitive settings like sudo, ssh and similar because these services are probably already configured with specifics to the existing machine.

This is probably going away with the new user management in CentOS7.

**Comment by vvidic** [comment]
On Wed, Jan 18, 2017 at 07:50:28AM -0800, Andrew R. Lake wrote:
> We should review this. I though everything we added was in sudoers.d and not in the main sudo.conf file.

There is etc/perfsonar_sudo with pssudo group:

```
# Installed by perfSONAR Toolkit. Allows anyone in pssudo group to have sudo on this machine
%pssudo        ALL=(ALL)       ALL
```

but also scripts/system_environment/enable_wheel_sudo adding:

```
%wheel        ALL=(ALL)       ALL
```

Guess we can drop the enable_wheel_sudo script and just support
pssudo group handling?

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by arlake228** [comment]
I think so. I think the enable_wheel_sudo is an artifact of old installs.

**Comment by vvidic** [comment]
Created a pull request #183 for this issue.
