### ISSUE TITLE
Enabling/disabling lsregistration daemon via Services tab in GUI

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/toolkit#150]
lsregistration is currently listed under services in the main page. It would be nice to have a possibility to enable/disable it under Services tab as other services. I think this component can be controlled by user with no harm to the proper functioning of the toolkit. There are users who want to disable it so it would be nice to have it in gui instead of CLI commands.

**Comment by arlake228** [comment]
Good chance we want to get rid of the services tab since not much more there anymore. Might make more sense as a toggle on the administrative information page which contains on the LS information that gets registered.

**Comment by apertome** [comment]
The services tab doesn't exist anymore.
