### ISSUE TITLE
Wrong rounding of the RAM info in the Host Information panel

### ISSUE THREAD

**Issue by tonin** [perfsonar/toolkit#151]
I have a VM with 3924156 bytes total memory.  The toolkit GUI right side panel shows 3 GB as RAM field where I was expecting 4 GB.

**Comment by tonin** [comment]
@apertome Do you know why there is similar code to what I have corrected in perfsonar/perl-shared@7d57206 in [web-ng/root/gui/services/index.cgi](https://github.com/perfsonar/toolkit/blob/master/web-ng/root/gui/services/index.cgi) at lines 232 and 259?

Do we need both?

**Comment by apertome** [comment]
@tonin There's no need for both so long as we agree on what value is being provided. Seems that we would need to change web-ng/root/gui/services/index.cgi  to use lib/perfSONAR_PS/NPToolkit/DataService/Host.pm to get the memory info

**Comment by tonin** [comment]
I guess my question is actually about the use of the `perfSONAR_PS::NPToolkit::DataService` library by the different components that we have (toolkit, lsreg, configdaemon, etc.).  It looks like there is a bit of redundancy (if I have the whole picture right...) and we should probably go for a round of refactoring.  This is in the code and in the configuration files too, some information we have in `lsregistrationdaemon.conf` is getting duplicated in `web_admin.conf` for example.
