### ISSUE TITLE
Error loading host details after a fresh Netinstall and yum update

### ISSUE THREAD

**Issue by apertome** [perfsonar/toolkit#154]
Reported by Szymon:

> Hi all. After a fresh install of netinstall ISO, then yum update, the gui shows constant Loading.. page and httpd/error_log throws error: " [cgi:error] [pid 13041] [client 150.254.170.65:65186] End of script output before headers: host.cgi, referer: http://150.254.160.17/toolkit/" Nothing more. Any ideas?

/var/log/httpd/error_log:  
[Wed Oct 19 14:59:48.069704 2016] [cgi:error] [pid 13187] [client 98.209.23.193:34649] End of script output before headers: host.cgi
[Wed Oct 19 15:00:19.451834 2016] [cgi:error] [pid 13043] [client 54.165.241.61:13529] End of script output before headers: host.cgi
[Wed Oct 19 15:00:29.666241 2016] [cgi:error] [pid 13132] [client 150.254.170.65:49417] End of script output before headers: host.cgi

andy
i was able to recreate locally and have debugged a bit. looks like maybe something is short-circuiting in the discover_primary_interface call of perfSONAR_PS::NPToolkit::DataService::Host’s get_details method

**Comment by arlake228** [comment]
I fixed this issue this morning and I am building the fix now. See perl-shared/93ea0af1bc9de50eb88d090344b469804b39dfa8
