### ISSUE TITLE
Latency/loss values not visible in Test results for fresh Netinstall

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/toolkit#155]
After a fresh Netinstall of 4.0RC1 and today's yum update (but in fact I noticed it also earlier but wasn't sure if it was related to some other issues) I configured a test to 3.5.1 host (throughput and one-way delay). The throughput values are immediately displayed in a Test Results table in the main page but latency/loss values are always n/a although there are tests running and the values are in the graph (see attachments). I'm viewing it in FF 49.0.1.
![test-no-loss-1](https://cloud.githubusercontent.com/assets/12281679/19552976/91dffa08-96b2-11e6-8b5b-fbce72f52b95.png)
![test-no-loss-2](https://cloud.githubusercontent.com/assets/12281679/19552977/91e00b88-96b2-11e6-9a08-fc1ca709cecf.png)

**Comment by arlake228** [comment]
Closing, i think there was a collection of fixes that addrssed this. Should re-open if becomes issue again
