### ISSUE TITLE
Loading values error for Test Results section for psc host tests

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/toolkit#156]
After a fresh Netinstall of 4.0RC1 and today's yum update I configured a test to 4.0RC1 host (throughput and one-way delay). Unfortunately none of the results is displayed in Test Results section of the main page. Instead it says  "Loading values". In the graph the results are there. I'm viewing it in FF 49.0.1.
![test-loading-error-1](https://cloud.githubusercontent.com/assets/12281679/19553409/78d0bc44-96b4-11e6-8c28-25ef2160fffd.png)
![test-loading-error-2](https://cloud.githubusercontent.com/assets/12281679/19553408/78cf2dde-96b4-11e6-842c-cbffc257d5a9.png)

**Comment by szymontrocha** [comment]
Seems that these value for tests to psc host finally appeared but it took it a couple of hours to appear/load for some reason. Which is strange as for the bwctl host the throughput values were there immediately after configuring the test. Not sure this is still an issue...

**Comment by apertome** [comment]
I have seen this as well, usually when the system load is high, but I'll see if there's more to it than that.

**Comment by szymontrocha** [comment]
After a day of collecting data the "loading values" has gone. So seems like it appears at the beginning, at first launch. But still it's a bit long as it is not for a few minutes but hours rather.

**Comment by marian-babik** [comment]
There are several boxes in WLCG testbed (on auto-updates) where "loading values" doesn't disappear even after couple of days after the update. The boxes don't have high load (each monitors ~ 5-6 others), e.g. http://perfsonar03-iep-grid.saske.sk/toolkit/, http://iut2-net3.iu.edu/toolkit/, https://psum05.aglt2.org/toolkit/

**Comment by arlake228** [comment]
As an update, the person who is likely to fix this is bogged down in SC stuff at the moment, so sorry there has not been movement. We are hoping to have a fix soon.

**Comment by apertome** [comment]
This has been fixed; actually, there is a two-part fix -- to the GUI, and to the pscheduler archiver, which was not correctly creating summaries in the archive in some cases ( see pscheduler#235 )
