### ISSUE TITLE
Manage auto-update for perfsonar-toolkit on Debian/Ubuntu

### ISSUE THREAD

**Issue by tonin** [perfsonar/toolkit#157]
We probably should take inspiration from http://docs.perfsonar.net/install_debian.html#step-5-auto-updates and add a toolkit configuration script for Debian and Ubuntu.

And we also need to consider what to do with people currently running perfsonar-(wheezy|jessie)-3.5 instead of perfsonar-(wheezy|jessie)-release.  The first ones will not get the automatic update to 4.0.

**Comment by vvidic** [comment]
I just changed the toolkit on Debian to use unattended-upgrades package instead of cron-apt as it seemed more common. Maybe the documentation should also be updated than?

**Comment by arlake228** [comment]
Has this been addressed?

**Comment by vvidic** [comment]
On Wed, Feb 01, 2017 at 07:22:20AM -0800, Andrew R. Lake wrote:
> Has this been addressed?

Yep, the auto-update works on the Debian side using unattended-upgrades
package.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by tonin** [comment]
We still need to correct the documentation though.  I added https://github.com/perfsonar/docs/issues/28 to track that.

**Comment by tonin** [comment]
I'm not sure the toolkit webinterface button for the auto-updates is working fine.  On my Ubuntu 14 host it stays unchecked although `60unattended-upgrades-perfsonar` contains `APT::Periodic::Unattended-Upgrade "1";`

But I also seem to have an issue with the NTP configuration on this same page, so it might be related.  To double check.

**Comment by vvidic** [comment]
Auto-update button should be functional now after the fix in perl-shared.
