### ISSUE TITLE
Remove or review on-demand testing tools from main page

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/toolkit#158]
Current main page of toolkit contains section "On-demand testing tools". But three of them are not working at all and requests are failing. They refer to old URLs like https://host/toolkit-old/gui/reverse_traceroute.cgi?function=ping:
Reverse ping
Reverse traceroute
Reverse tracepath 
Suggestion to remove them from this section of toolkit if they are no longer supported.

**Comment by arlake228** [comment]
They are still supported, just the link should point to /toolkit instead of /toolkit-old. Will in commit momentarily.
