### ISSUE TITLE
Wrong location for web-admin configuration files?

### ISSUE THREAD

**Issue by tonin** [perfsonar/toolkit#160]
The current perfsonar-toolkit bundle installation places the webadmin configuration file at `/usr/lib/perfsonar/web-ng/etc/`   Is this intentional?  Shouldn't this be in `/etc/perfsonar/web-ng` or similar?

**Comment by apertome** [comment]
It was done this way to be consistent with how the old toolkit GUI stored its config. I don't think there's any reason it couldn't live in /etc/perfsonar/ somewhere, either where you suggest or /etc/perfsonar/toolkit/web (maybe we get rid of -ng?)

**Comment by arlake228** [comment]
Could we just do a symlink of /etc/perfsonar/toolkit/web to /usr/lib/perfsonar/web-ng/etc/? It would save the hassle of having to shift config files around yet again.

**Comment by apertome** [comment]
That would work for me ...
