### ISSUE TITLE
Handle new pScheduler syslog destination

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/toolkit#161]
https://github.com/perfsonar/pscheduler/issues/209 has log output from pScheduler point to `local5` by default.  pScheduler has been set up to direct that log to `/var/log/pscheduler/pscheduler.log` and make sure that file is rotated.

The GUI will need to be adjusted to get the pScheduler log from there instead of `/var/log/perfsonar`, which is where it looks now.

**Comment by apertome** [comment]
Got another request for this from @bltierney today, maybe we can do this in time for 4.0?
