### ISSUE TITLE
Verify if NTP service is properly initialising

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/toolkit#163]
Seems like after a fresh ISO installation ntpd service is not started. Even after NTP configuration in GUI it's made active but to permanent. After host restart it's not running again.

Status after fresh install or restart:
[root@localhost psudouser]# systemctl status ntpd
● ntpd.service - Network Time Service
   Loaded: loaded (/usr/lib/systemd/system/ntpd.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
[root@localhost psudouser]# systemctl is-enabled ntpd
enabled
[root@localhost psudouser]# ps -ef|grep ntpd
root      4154  4089  0 15:59 pts/0    00:00:00 grep --color=auto ntpd

After config in GUI and saving changes:
[root@localhost psudouser]#  systemctl status ntpd
● ntpd.service - Network Time Service
   Loaded: loaded (/usr/lib/systemd/system/ntpd.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2016-11-03 16:01:34 CET; 16s ago
  Process: 4588 ExecStart=/usr/sbin/ntpd -u ntp:ntp $OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 4589 (ntpd)
   CGroup: /system.slice/ntpd.service
           └─4589 /usr/sbin/ntpd -u ntp:ntp -g

Nov 03 16:01:34 localhost.localdomain systemd[1]: Starting Network Time Service...
Nov 03 16:01:34 localhost.localdomain ntpd[4589]: proto: precision = 0.140 usec
Nov 03 16:01:34 localhost.localdomain ntpd[4589]: 0.0.0.0 c01d 0d kern kernel time sync enabled
Nov 03 16:01:34 localhost.localdomain systemd[1]: Started Network Time Service.
[root@localhost psudouser]# systemctl is-enabled ntpd
enabled
[root@localhost psudouser]# ps -ef|grep ntpd
ntp       4589     1  0 16:01 ?        00:00:00 /usr/sbin/ntpd -u ntp:ntp -g
root      4625  4089  0 16:01 pts/0    00:00:00 grep --color=auto ntpd
[root@localhost psudouser]#

After host restart see beginning :-)

**Comment by arlake228** [comment]
NTP is indeed enabled, but it looks like chronyd is also, which supersedes ntp and prevents it from starting. I will fix this for new installs. To fix on your existing system run `systemctl disable chronyd` and then try a reboot. ntp should come up immediately.
