### ISSUE TITLE
Graph listing stuck on "loading values" for latency tests

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#164]
If you got to http://nettest.lbl.gov/toolkit/ you'll see that everything that is a latency test is stuck on "loading values". If you click on "Details" the graphs load. I don't see any javascript errors on the console. I can't tell if its an error or they are all just busy retrieving. Reporting here so we remember to take a look. Let me know if there are any logs I can share.

**Comment by szymontrocha** [comment]
I think this is a duplication of #156 I experienced (and experience in rc2) the same

**Comment by apertome** [comment]
I have seen this as well, usually when the system load is high, but I'll see if there's more to it than that. On particularly busy MAs it can be a challenge to load all that data (this is why we moved it off to another function that doesn't block the whole test listing from blocking). I'll try to get a better sense of what's going on here.

**Comment by apertome** [comment]
Let's leave both issues open for now; I think that they're probably the same issue, but it's not entirely clear yet.

**Comment by apertome** [comment]
Adding Lisa as she will likely help with this

**Comment by szymontrocha** [comment]
My host is a fersh one with just 4 tests configured. Although at a very initial stage of configuration - after the fresh install so maybe the database is very busy behind, at the beginning

**Comment by arlake228** [comment]
Another data point. http://psum05.aglt2.org seems to be doing the same

**Comment by marian-babik** [comment]
Actually, we have more of them doing the same:
http://iut2-net3.iu.edu/toolkit/
http://mwt2-ps03.campuscluster.illinois.edu/toolkit/
http://netmon1.atlas-swt2.org/toolkit/
http://uct2-net3.mwt2.org/toolkit/
http://perfsonar03-iep-grid.saske.sk/toolkit/

**Comment by arlake228** [comment]
This duplicates #156 so merging
