### ISSUE TITLE
ABRT error at first login

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/toolkit#165]
login as: root
root@150.254.160.17's password:
Last failed login: Fri Nov  4 12:55:09 CET 2016 from 116.31.116.30 on ssh:notty
There were 6 failed login attempts since the last successful login.
Welcome to the perfSONAR Toolkit v4.0

You may create accounts to manage this host through the web interface by running the following as root:

  /usr/lib/perfsonar/scripts/nptoolkit-configure.py

The web interface should be available at:

https://150.254.160.17/toolkit
ABRT has detected 1 problem(s). For more info run: abrt-cli list
There isn't a perfSONAR Website Administrator defined.
Enter the user whose account you'd like to add. Just hit enter to exit:

[root@localhost ~]# abrt-cli list
id 66cdadd71377578abd8aa8f5ea98b680c9e3121c
reason:         pidfile.py:41:__exit__:OSError: [Errno 13] Permission denied: '/var/run/pscheduler-ticker.pid'
time:           Fri 04 Nov 2016 12:54:46 PM CET
cmdline:        /usr/bin/python /usr/libexec/pscheduler/daemons/ticker --daemon --pid-file /var/run/pscheduler-ticker.pid --dsn @/etc/pscheduler/database/database-dsn
package:        pscheduler-server-1.0-0.15.rc2.el7.centos
uid:            1000 (pscheduler)
count:          4
Directory:      /var/spool/abrt/Python-2016-11-04-12:54:46-5960

The Autoreporting feature is disabled. Please consider enabling it by issuing
'abrt-auto-reporting enabled' as a user with root privileges
[root@localhost ~]#

**Comment by szymontrocha** [comment]
The problem appeared also after today's yum update (not sure it is still the same):
[psudouser@localhost ~]$ sudo bash
[sudo] password for psudouser:
ABRT has detected 1 problem(s). For more info run: abrt-cli list --since 1478788183
[root@localhost psudouser]# abrt-cli list --since 1478788183
id 66cdadd71377578abd8aa8f5ea98b680c9e3121c
reason:         pidfile.py:41:__exit__:OSError: [Errno 13] Permission denied: '/var/run/pscheduler-ticker.pid'
time:           Fri 04 Nov 2016 12:54:46 PM CET
cmdline:        /usr/bin/python /usr/libexec/pscheduler/daemons/ticker --daemon --pid-file /var/run/pscheduler-ticker.pid --dsn @/etc/pscheduler/database/database-dsn
package:        pscheduler-server-1.0-0.15.rc2.el7.centos
uid:            1000 (pscheduler)
count:          12
Directory:      /var/spool/abrt/Python-2016-11-04-12:54:46-5960

The Autoreporting feature is disabled. Please consider enabling it by issuing
'abrt-auto-reporting enabled' as a user with root privileges
[root@localhost psudouser]#

**Comment by mfeit-internet2** [comment]
Not sure what's going on with the PID file being denied.  The init script for each of the daemons creates and chowns the file so it's writable:

```
start() {
    ...
    touch "$pidfile"
    chown "$proguser.$proguser" "$pidfile"
    ...
    su $proguser \
       -c "$exec --daemon --pid-file '$pidfile' --dsn '@$config'" \
        >> "$logfile" 2>&1 &
    retval=$?
    success
    echo
}

```
...and the files get created properly on my CentOS 7 systems:

```
# ls -alh /var/run/pscheduler-*
-rw-r--r--. 1 pscheduler pscheduler 5 Nov  9 11:21 /var/run/pscheduler-archiver.pid
-rw-r--r--. 1 pscheduler pscheduler 5 Nov  9 11:21 /var/run/pscheduler-runner.pid
-rw-r--r--. 1 pscheduler pscheduler 5 Nov  9 11:21 /var/run/pscheduler-scheduler.pid
-rw-r--r--. 1 pscheduler pscheduler 5 Nov  9 11:21 /var/run/pscheduler-ticker.pid
```

Worked on CentOS 6 last I tried it, too.

**Comment by arlake228** [comment]
I didn't see this on my newer installs anymore. When i do the next round of clean installs in the next day or so I will close this if it doesn't pop back-up.

**Comment by arlake228** [comment]
Closing, seems to have disappeared and haven't see in many months. Can re-open if it shows up again.
