### ISSUE TITLE
Updates to sysctl for CentOS 7 and Debian 8

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#166]
On CentOS 7 and Debian 8 (not CentOS 6) we should update scripts/configure_sysctl to do the following:

- set `net.core.default_qdisc = fq`
-  It should NOT set `net.core.netdev_max_backlog` on CentOS 7 and Debian 8

**Comment by bltierney** [comment]
I already made this change, but someone should review. I might have made the change for CentOS 6 too, which is not right.
