### ISSUE TITLE
esmond backup script enhancements

### ISSUE THREAD

**Issue by daldoyle** [perfsonar/toolkit#170]
From Michael Petry on the perfsonar-users list...

TLDR -
 
1. looks like we need to detect and handle an edge case for a backup without any data, may just need to skip that step if so

2. before doing any backups, clear out any prior ones (probably with a confirmation just in case)

> I've tried using the backup and restore script in 
> /usr/lib/perfsonar/scripts
> 
> with limited success.  Here are a few things:
> 
> 1) If you do a backup (with data "-d") of a clean system (no tests configured) you get an error
> 
> root@oit-82-33 cassandra]#  /usr/lib/perfsonar/scripts/ps-toolkit-migrate-backup.sh -d ~petry/backuptest
> Backing-up users...[SUCCESS]
> Backing-up groups...[SUCCESS]
> Backing-up passwords...[SUCCESS]
> Backing up administrative users...[SUCCESS]
> Backing-up toolkit configuration...[SUCCESS]
> Backing-up bwctl-server configuration...[SUCCESS]
> Backing-up owamp-server configuration...[SUCCESS]
> Backing-up pScheduler configuration...[SUCCESS]
> Backing-up NTP configuration...[SUCCESS]
> Backing-up cassandra data...Unable to snapshot cassandra database
> 
> 
> Digging into the bash script, it fails on doing the node tool command.
> Its a corner case, but annoying.  (Once there is data, there is another problem  see 2.)
> 
> Notetool on clean system
> ---------------------------------
> 
> nodetool snapshot esmond -t esmond_snapshot
> Requested creating snapshot for: esmond 
> Exception in thread "main" java.io.IOException: Keyspace esmond does not exist
> 	at org.apache.cassandra.service.StorageService.getValidKeyspace(StorageService.java:2298)
> .
> .
> .
> 
> 
> 2) do the same backup on a system with data.  Do it a second time and you'll get.
> the script should probably clean up after itself and do a "nodetool clearsnapshot"
> 
> [root@ps-10g-sdmz scripts]# /usr/lib/perfsonar/scripts/ps-toolkit-migrate-backup.sh -d ~petry/backuptest
> Backing-up users...[SUCCESS]
> Backing-up groups...[SUCCESS]
> Backing-up passwords...[SUCCESS]
> Backing up administrative users...[SUCCESS]
> Backing-up toolkit configuration...[SUCCESS]
> Backing-up bwctl-server configuration...[SUCCESS]
> Backing-up owamp-server configuration...[SUCCESS]
> Backing-up pScheduler configuration...[SUCCESS]
> Backing-up NTP configuration...[SUCCESS]
> Backing-up cassandra data...Unable to snapshot cassandra database
> [root@ps-10g-sdmz scripts]# nodetool snapshot esmond -t esmond_snapshot
> Requested creating snapshot for: esmond 
> Exception in thread "main" java.io.IOException: Snapshot esmond_snapshot already exists.
> .
> .
> .
>

**Comment by arlake228** [comment]
Fixed by vvidic in pull request
