### ISSUE TITLE
toolkit UI displays loopback interface as primary in certain static IP configuration scenarios

### ISSUE THREAD

**Issue by somedatapacket** [perfsonar/toolkit#173]
In a scenario where a VMWare host is configured with a static IP address and manually-entered hostname via the CentOS 7 installer GUI, the hostname is configured in /etc/hostname but is not appended to 127.0.0.1 or ::1 /etc/hosts entries. Once the toolkit installation is complete, navigating to the toolkit using http://<ip address>/toolkit succeeds, but the toolkit UI shows the loopback interface as primary and displays localhost in relevant fields.

Here's the interface list:
<img width="647" alt="interface_list" src="https://cloud.githubusercontent.com/assets/2058357/20718707/97d9634c-b627-11e6-8a20-3ba0eab45dd7.png">

Here's where it lists loopback as primary:
<img width="208" alt="primary_interface" src="https://cloud.githubusercontent.com/assets/2058357/20718708/97db080a-b627-11e6-9f92-46c8beb997ac.png">

Here's what the toolkit URL looks like in the SSH message:
<img width="293" alt="toolkit_url" src="https://cloud.githubusercontent.com/assets/2058357/20718709/97db6304-b627-11e6-8660-e1131a959e30.png">

**Comment by arlake228** [comment]
Assigning to self because I think its related to other issues assigned to me.

**Comment by arlake228** [comment]
Fixed in perfsonar/perl-shared@3cf4ecf6c2407ed7ffe3465b51b2415df74f4356. Probably do some more clean-up when address #90.
