### ISSUE TITLE
Trailing whitespace in config GUI leads to address with escaped quotes

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#174]
If you enter a host in the configuration GUI and leave trailing whitespace in the field it will give you something like this in /etc/perfsonar/meshconfig-agent-tasks.conf:

``address   \"perfsonardev0.internet2.edu \"``

The escaped quotes lead to an error creating the test. The GUI should strip that trailing whitespace so the quotes are not added.

**Comment by apertome** [comment]
This is fixed now. I also updated the shared pointer -- the Toolkit hadn't picked up the change that fixed the "unable to save" error
