### ISSUE TITLE
Risk on meshconfig_agent_tasks changes

### ISSUE THREAD

**Issue by igarny** [perfsonar/toolkit#176]
Hi,

Generally the risk is small, since it relates to configuration available only for pS 4.0.

https://github.com/perfsonar/toolkit/blob/master/scripts/system_environment/configure_owamp_testports

The script above uses a fixed reference to a configuration file (the _tasks.conf), which is a parameter in /etc/perfsonar/meshconfig-agent.conf

Probably it would be better extracting the param similar to:
sed -n -e '/^\s*tasks_conf/p' meshconfig-agent.conf |  sed 's/.*tasks_conf\s*\(.*\)$/\1/g'

Please note this command will extract only if the parameter is defined. There is the possibility that the defaults are applied.

Regards,
Ivan

**Comment by arlake228** [comment]
Closing. I do acknowledge what's described is possible though it seems highly unlikely and probably not worth the risk of breaking something by trying to extract a property that nobody uses.
