### ISSUE TITLE
suggestion: manage logrotation for perfSONAR separately 

### ISSUE THREAD

**Issue by igarny** [perfsonar/toolkit#177]
https://github.com/perfsonar/toolkit/blob/master/scripts/system_environment/configure_syslog_local5_location

The script above modifies the /etc/logrotate.d/syslog, which is a configuration file of the OS.

Wouldn't it be more reasonable to dedicate a perfsonar config file in /etc/logrotate.d?
Current solution adds superficial complexity for configuration management systems, where there are separate procedures for OS configuration management.

Regards,
Ivan

**Comment by arlake228** [comment]
Fixed by valentin's pull request.
