### ISSUE TITLE
Ability to 'clone' a running node/smarter backups

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#18]
_From @arlake228 on March 14, 2015 12:35_

Original [issue 991](https://code.google.com/p/perfsonar-ps/issues/detail?id=991) created by arlake228 on 2014-10-06T13:39:27.000Z:

During the mailing list traffic related to shell shock, several people have noted they would like some of the following features:
- Smarter backups.  Right now we have the ability to back up data and config - maybe doing this via cron and allowing the files to be written to some specific removable disk or rsync'd to another location?  In the case of the later - would recommend we start providing the hpc patch for SSH to improve that performance.  
- Related to the first - the ability to 'clone' an existing machine.  Lets say someone is replacing hardware, or looking to establish a hot copy.  Using the backup data, could we automate the build/re-configuration of a new host to have all the same properties as the prior?

_Copied from original issue: perfsonar/project#989_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=991#c1) originally posted by arlake228 on 2014-10-06T20:12:17.000Z:

I wonder if using the regular testing's support for multiple MAs to store data in the local MA, and a backup one would work for backing up the data. You'd just have 2 MAs with, theoretically, the same data in each.

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=991#c2) originally posted by arlake228 on 2014-10-06T20:20:32.000Z:

Multiple MAs would theoretically work. I also wonder if leveraging replication features of cassandra and postgresql would be better. I've been talking with David Ripley at IU about their pSB to esmond migration and this is something they are looking at. Maybe we could at least pull some best common practices out of what they do. Likely we'll need a menu of options for people.

**Comment by arlake228** [comment]
Comment [#3](https://code.google.com/p/perfsonar-ps/issues/detail?id=991#c3) originally posted by arlake228 on 2015-01-30T19:41:33.000Z:

&lt;empty&gt;

**Comment by mfeit-internet2** [comment]
> I also wonder if leveraging replication features of cassandra and postgresql would be better.

Replication is a terrible choice for backup.  If something damages a database from inside (e.g., `DELETE FROM TABLE t`), the only thing preventing the same transaction from being applied to the replicas is a network outage.  It's also a support nightmare unless we spend a lot of time making it end-user-friendly.

The clean thing to do would be giving each part of the system the equivalent of a (de)serializer.  It's given a private directory and dumps whatever it needs to restore state there.  If the component uses PostgreSQL as a data store, it can use pg_dump to dump its database and pg_restore to restore it when given the contents of the directory.

**Comment by arlake228** [comment]
This is a pretty old issue, so take the comments with a grain of salt. To provide some context, we had a script like this that needs to be updated which did what you describe for an older version of the code (3.2 and 3.3):
https://github.com/perfsonar/toolkit/blob/master/scripts/ps-toolkit-migrate-backup.sh
ps-toolkit-migrate-backup.sh
https://github.com/perfsonar/toolkit/blob/master/scripts/ps-toolkit-migrate-restore.sh

We have since documented how to create snapshots of the database for both cassandra and postgresql (including how to use pg_dump/pg_restore): http://docs.perfsonar.net/multi_ma_backups.html#backing-up-and-restoring-data

Some of these methods could be rolled into scrips like the above.t.

**Comment by bltierney** [comment]
can this be closed?

**Comment by arlake228** [comment]
Just needs testing at this point.

**Comment by arlake228** [comment]
This appears to work just like intended. Only thing I noticed is that it seems to work just fine on bundles other than toolkit, so should probably move it to perfsonar-toolkit-install with other utility scripts so others have access to it. Leaving open for those packaging changes to be made.
