### ISSUE TITLE
pS is overtaking management of SSH rules in FW

### ISSUE THREAD

**Issue by igarny** [perfsonar/toolkit#180]
The below rule I found in the latest FW config: https://github.com/perfsonar/toolkit/blob/dfd46e28dd9a6781b76d0686a8f3d038eeac29a4/etc/perfsonar_firewall_settings.conf 

-A perfSONAR -p tcp -m state --state NEW,ESTABLISHED -m tcp --dport 22 -j ACCEPT

This can in certain circumstances lead to fail2ban overruling.
My suggestion is to check if there are already "--dport 22" rules, before messing with user's FW config.
Generally management of SSH should be none of pS business.

Regards,
Ivan

**Comment by arlake228** [comment]
Assigning to vvdic to see if anything better we can do.

**Comment by vvidic** [comment]
Don't know, was there some security issue behind adding ssh and other rules in 34ac489403f074a3e81dbed9d3b7f8bf7baca94b?

```
# Allow Loopback
-A perfSONAR -i lo -j ACCEPT

# Accept existing and related connections
-A perfSONAR -m state --state ESTABLISHED,RELATED -j ACCEPT

# Incoming SSH - TCP Port 22
-A perfSONAR -m state --state NEW,ESTABLISHED -m tcp -p tcp --dport 22 -j ACCEPT

# DHCPv6
-A perfSONAR -m state --state NEW -m udp -p udp --dport 546 --sport 547 -j ACCEPT

# Make sure we reject traffic
-A INPUT -j REJECT

# Allow outgoing from loopback
-A OUTPUT -o lo -j ACCEPT

# Make sure we reject FORWARD traffic
-A FORWARD -j REJECT
```

**Comment by vvidic** [comment]
Also I'm not sure how it would override fail2bain since it always inserts in the beginning:

```
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  499 40536 f2b-sshd   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           multiport dports 22 
 1414  681K perfSONAR  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0           state RELATED,ESTABLISHED 
    0     0 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           state NEW tcp dpt:22 
    0     0 REJECT     all  --  *      *       0.0.0.0/0            0.0.0.0/0           reject-with icmp-host-prohibited 
```

Ivan, how does this look on your side?

**Comment by igarny** [comment]
Hi my point with the ticket was a bit different.
Every time we push a firewall change, there are always people who realize their specific configuration is gone or bypassed.
For sure fail2ban on every service restart reorganizes and reapplies its FW rules in the very beginning.

The idea behind this ticket is about people who have their own specific rules for SSH connections. With our config added in front this means, their rules will be silently bypassed in the PERFSONAR chain.

**Comment by vvidic** [comment]
Pull request #202 skips the SSH rule on RHEL6 if there is some mention of SSH in INPUT chain.

**Comment by arlake228** [comment]
pull request merged
