### ISSUE TITLE
Debian: Translate RPM references to deb packages in the web interfaces

### ISSUE THREAD

**Issue by tonin** [perfsonar/toolkit#188]
In the web interface, in the Host Details popup, there is a wording of "Toolkit RPM version", this should be change to "Toolkit deb version".  We should check if there are other similar changes that needs to be done to labels and information displayed.

**Comment by mfeit-internet2** [comment]
"Toolkit package version" might be a suitable generic replacement.

**Comment by tonin** [comment]
Yep.  BTW, we probably need to consider both versions labels and make them less confusing.  Maybe have listed:

- **pS version** (for the bundle package version)
- **Toolkit package version** (for the actual toolkit package version)

**Comment by vvidic** [comment]
Updated the labels in pull request #190, did not touch variable names at this point.

**Comment by tonin** [comment]
Looks good to me, thanks!
