### ISSUE TITLE
New Toolkit Install does not open port 861

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#189]
The firewall script tries to open "owamp-control", but it appears to be named "owamp". The opposite was true a week or so ago. We need to figure out what is going on with the firewall rules and why it changed.

**Comment by vvidic** [comment]
Pull request #191 should fix this.

**Comment by arlake228** [comment]
@vvidic: Do you have any idea why owamp-control was working previously? I understand the fix, its just odd this seems to be a moving target.

**Comment by arlake228** [comment]
Closing, should be fixed now. Will re-open if it shows-up again.

**Comment by mfeit-internet2** [comment]
John is still having difficulties with this on his CentOS 7 system.

**Comment by somedatapacket** [comment]
Oddly, I find that `firewall-cmd --zone=public --add-service=owamp-control --permanent` appears to fail with `Error: INVALID_SERVICE: 'owamp-control' not among existing services`

**Comment by apertome** [comment]
In the short term, you should be able to accomplish this by specifying the port number directly.

**Comment by somedatapacket** [comment]
That's done, thanks @apertome

**Comment by vvidic** [comment]
On Tue, Feb 07, 2017 at 09:19:18AM -0800, Mark Feit wrote:
> John is still having difficulties with this on his CentOS 7 system.

Can you provide the version and contents of the perfsonar-toolkit-security
package that is installed?

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by somedatapacket** [comment]
Installed Packages
Name        : perfsonar-toolkit-security
Arch        : noarch
Version     : 4.0
Release     : 0.12.rc3.el7.centos
Size        : 14 k
Repo        : installed
From repo   : Internet2-staging

**Comment by somedatapacket** [comment]
/etc/perfsonar/toolkit/default_system_firewall_settings.conf
/etc/perfsonar/toolkit/old_firewall_settings.conf
/etc/perfsonar/toolkit/perfsonar_firewall_settings.conf
/etc/perfsonar/toolkit/perfsonar_firewalld_settings.conf
/usr/lib/firewalld/services/bwctl.xml
/usr/lib/firewalld/services/ndt.xml
/usr/lib/firewalld/services/npad.xml
/usr/lib/firewalld/services/oppd.xml
/usr/lib/firewalld/services/traceroute.xml
/usr/lib/perfsonar/scripts/configure_firewall

**Comment by vvidic** [comment]
On Wed, Feb 08, 2017 at 05:22:25AM -0800, somedatapacket wrote:
> /etc/perfsonar/toolkit/default_system_firewall_settings.conf
> /etc/perfsonar/toolkit/old_firewall_settings.conf
> /etc/perfsonar/toolkit/perfsonar_firewall_settings.conf
> /etc/perfsonar/toolkit/perfsonar_firewalld_settings.conf
> /usr/lib/firewalld/services/bwctl.xml
> /usr/lib/firewalld/services/ndt.xml
> /usr/lib/firewalld/services/npad.xml
> /usr/lib/firewalld/services/oppd.xml
> /usr/lib/firewalld/services/traceroute.xml
> /usr/lib/perfsonar/scripts/configure_firewall

Ok, renamed owamp-control.xml was not included in the package,
will send a pull request to fix this.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by tonin** [comment]
Thanks Valentin.  Can someone with a CentOS7 host review Valentin PR?  See https://github.com/perfsonar/toolkit/pull/196

**Comment by somedatapacket** [comment]
@tonin @vvidic reinstalling perfsonar-toolkit-security (or all of perfsonar-toolkit) does not appear to cause /etc/firewalld/services to populate, nor does running /usr/lib/perfsonar/configure_firewall. Is this expected? What's the best way to test this further?

**Comment by vvidic** [comment]
On Thu, Feb 09, 2017 at 01:03:27PM -0800, somedatapacket wrote:
> @tonin @vvidic reinstalling perfsonar-toolkit-security (or all of
> perfsonar-toolkit) does not appear to cause /etc/firewalld/services to
> populate, nor does running /usr/lib/perfsonar/configure_firewall. Is this
> expected? What's the best way to test this further?

The fix in not available in staging yet but you can try the package
from nightly:

http://downloads.perfsonar.net/redhat/branches/nightly/rpms/el7/x86_64/main/RPMS/perfsonar-toolkit-security-4.0-0.12.rc3.el7.centos.1324.977dd40fd3e52e3548cc9c15b1c883a2249e3034.noarch.rpm

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by arlake228** [comment]
Closing for now since should be fixed in nightly. will re-open if still not the case.

**Comment by mfeit-internet2** [comment]
This is still a problem on the staging systems I installed using the toolkit bundle.  Reopening.

**Comment by arlake228** [comment]
Have we been able to reproduce this recently?

**Comment by vvidic** [comment]
I think the problem is that firewalld is running already when installing packages and it doesn't know about new xml files installed by `perfsonar-toolkit-security`. Reloading the firewalld before configuring should fix this problem. Will send a PR...
