### ISSUE TITLE
Warning when longitude or latitude is set to 0 or if using decimal separator different from the dot

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#19]
_From @arlake228 on March 14, 2015 12:37_

Original [issue 997](https://code.google.com/p/perfsonar-ps/issues/detail?id=997) created by arlake228 on 2014-10-09T14:38:02.000Z:

When one wants to set the latitude or longitude parameter to 0 through the web interface, those fields are marked in yellow as if it was not configured.  But 0 should be a valid value, although uncommon.

There is also a small LOCALE issue.  If one has a browser language setting where the decimal separator is not the dot '.', the javascript dialogue wants you to fill the longitude and latitude fields with your LOCALE separator.  When the dialogue gets validated, the main page then displays the value with the dot as separator, regardless of your language settings.  So far, no problem.  But when you get to edit the informations again, the value is still using the dot as separator and javascript marks the field in yellow, stating that the value is not a number (because it should here use the LOCALE decimal separator), so you need to replace the dot with your LOCALE separator to get a correct entry.

To reproduce the behaviour, just put some other language, French for example, as your main browser language and reload the settings page (French is using the coma ',' as decimal separator).  This might be a dojo issue.

_Copied from original issue: perfsonar/project#995_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=997#c1) originally posted by arlake228 on 2014-10-09T15:15:28.000Z:

A similar issue exist with the thousands separator when, for example, filling the 'Size of packet' parameter for ping tests.  My LOCALE asks me to use space as a thousand separator, but web page somehow forbids it.

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=997#c2) originally posted by arlake228 on 2015-01-27T15:26:07.000Z:

&lt;empty&gt;

**Comment by sowmyab** [comment]
There is a plan to add more validation to the new toolkit interface. This can be part of that task.

**Comment by vvidic** [comment]
I don't get a javascript warning but host.cgi reports an error:
```
Input parameter latitude only accepts decimal numbers.
```
Two pull requests for this issue are here:

https://github.com/perfsonar/toolkit/pull/91
https://github.com/perfsonar/perl-shared/pull/9

**Comment by apertome** [comment]
Valentin's PRs fixed this issue. Thanks! Closing.
