### ISSUE TITLE
Ubuntu: NTP server configuration through web toolkit gui not working

### ISSUE THREAD

**Issue by tonin** [perfsonar/toolkit#194]
On my Ubuntu 14 host with the full toolkit installed, I cannot edit the NTP configuration from the Admin/Host configuration tab.  The default Ubuntu NTP servers are shown by the webgui (ntp.ubuntu.com, 0.ubuntu.pool.ntp.org through to 3.ubuntu.pool.ntp.org), I can delete those, but the **Select the closest servers** then does nothing.

Moreover, when trying to save a manual configuration, the webgui answers **Error - Problem saving configuration: Problem generating NTP configuration**

**Comment by vvidic** [comment]
Init for config-daemon was not dropped when adding other toolkit init scripts. As a result config-daemon was not running and saving configuration reporting errors.
