### ISSUE TITLE
Hostname field in add host to test allows random text

### ISSUE THREAD

**Issue by sowmyab** [perfsonar/toolkit#197]
The test configuration page accepts random text for host name.

<img width="1001" alt="screen shot 2017-02-08 at 1 35 41 pm" src="https://cloud.githubusercontent.com/assets/4259604/22754212/662a9ca2-ee04-11e6-8e98-fb432808c406.png">

**Comment by apertome** [comment]
Committed a fix in b873a8b33eff1ffd8d778338281bc2919547779e
