### ISSUE TITLE
When selecting closes NTP server, notification message gets cut off

### ISSUE THREAD

**Issue by sowmyab** [perfsonar/toolkit#198]
This was in Chrome browser
<img width="1680" alt="screen shot 2017-02-08 at 3 52 38 pm" src="https://cloud.githubusercontent.com/assets/4259604/22759117/e7b3e00a-ee16-11e6-9568-0c6a6e8c9756.png">

**Comment by tonin** [comment]
Similar in FF 51 - OSX 10.11
![screen](https://cloud.githubusercontent.com/assets/484879/22759699/b5668822-ee53-11e6-97c7-fdff2882e235.png)

**Comment by apertome** [comment]
Fixed.
