### ISSUE TITLE
Looped link to etc in /usr/lib/perfsonar/web-ng/

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/toolkit#209]
Not sure it still exists as I noticed in on my toolkit rc2 host updated frequently from staging but:

[psudouser@localhost ~]$ cd /usr/lib/perfsonar/web-ng/
etc/       root/      templates/
[psudouser@localhost ~]$ ls -la
total 12
drwxr-xr-x. 2 perfsonar perfsonar  87 Mar  8 10:08 .
drwxr-xr-x. 5 root      root       43 Jan 18 10:41 ..
lrwxrwxrwx  1 root      root       29 Feb 24 12:08 etc -> /usr/lib/perfsonar/web                                    -ng/etc
-rw-r--r--  1 perfsonar perfsonar 650 Mar  7 20:46 logger.conf
-rw-r--r--  1 perfsonar perfsonar 700 Mar  7 20:46 test_config_defaults.conf
-rw-r--r--  1 perfsonar perfsonar 514 Mar  7 20:46 web_admin.conf
[psudouser@localhost etc]$ cd etc
[psudouser@localhost etc]$ ls
etc  logger.conf  test_config_defaults.conf  web_admin.conf
[psudouser@localhost etc]$ cd etc/
[psudouser@localhost etc]$ cd etc/
[psudouser@localhost etc]$ pwd
/usr/lib/perfsonar/web-ng/etc/etc/etc/etc

**Comment by apertome** [comment]
Interesting -- I haven't seen this, maybe @arlake228 has some insight?

**Comment by apertome** [comment]
Adding @arlake228 per our meeting this morning he'll be looking at this
