### ISSUE TITLE
remove NTD and NPAD ports from default firewall config

### ISSUE THREAD

**Issue by bltierney** [perfsonar/toolkit#212]
no longer need NTD and NPAD ports open.

**Comment by bltierney** [comment]
port 8096 too. The LS no longer uses that port.

**Comment by vvidic** [comment]
On Sun, Mar 26, 2017 at 08:38:38AM -0700, Brian Tierney wrote:
> port 8096 too. The LS no longer uses that port.

I only see 8090 for OPPD, maybe 8096 was never in the default firewall config?

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by vvidic** [comment]
Create pull request #214

**Comment by arlake228** [comment]
Added self to review pull request.
