### ISSUE TITLE
If there is ~no loss, the graph goes from 0 to 0 and the line is at the top

### ISSUE THREAD

**Issue by lisaens** [perfsonar/toolkit#217]
Always set the scale from 0.00 to 0.01 in this case? 

![screen shot 2017-03-30 at 12 27 55 pm](https://cloud.githubusercontent.com/assets/18015225/24523161/25094632-1560-11e7-9d6e-43bb0ff4e0c1.png)

**Comment by apertome** [comment]
This has already been fixed.
