### ISSUE TITLE
More User Experience Improvements

### ISSUE THREAD

**Issue by lisaens** [perfsonar/toolkit#218]
- [x] Configuration - Host page - Having the dropdown for NTP servers open when something is deleted is confusing.

- [x] I'd like to see graph areas brighter white or something, to divide up the space on the page more (this is part of the graphs, a separate package at https://github.com/perfsonar/graphs)

- [x] It’d be really useful to be able to mouse over Test Members on the Configure-Tests page and see the list of members (this one is more complicated, optional)

**Comment by apertome** [comment]
- [ ] check for new version of select2 widget

**Comment by apertome** [comment]
The first issue (NTP server dropdown) is a behavior of the widget, not something we can easily change.

**Comment by apertome** [comment]
The test members part is more complicated than is probably worthwhile to implement
