### ISSUE TITLE
Add additional regular_testing parameters to GUI

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#22]
_From @arlake228 on March 14, 2015 12:44_

Original [issue 1028](https://code.google.com/p/perfsonar-ps/issues/detail?id=1028) created by arlake228 on 2014-12-22T17:11:01.000Z:

<b>What steps will reproduce the problem?</b>

Configure a regular throughput test to a given host with omit_interval to omit (e.g.) the first 2 seconds of the results, for TCP ramp-up

<b>What is the expected output? What do you see instead?</b>

At the moment you can only configure it by manually editing regular_testing.conf

&lt;parameters&gt;
    ...
    omit_interval 2
&lt;/parameters&gt;

I would like to be able to do this through the GUI; or at least have the setting shown in the GUI when you view the test parameters.

<b>What version of the product are you using? On what operating system?</b>

perfsonar PS 3.4.1

<b>Please provide any additional information below.</b>

_Copied from original issue: perfsonar/project#1026_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=1028#c1) originally posted by arlake228 on 2015-01-27T15:04:46.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=1028#c2) originally posted by arlake228 on 2015-01-30T18:54:36.000Z:

Need to think about overall what we display in admin GUI. Should we have an advanced options tab?

**Comment by apertome** [comment]
Moving to 3.6 along with the new regular testing gui

**Comment by candlerb** [comment]
I would like to expand this issue a little to include all regular_testing configuration options.

There are a bunch of regular_testing properties which are not seen in the GUI, but which can be set (e.g.) by the mesh configuration.

Example: if you set `force_bidirectional 0` in the mesh config, this generates `send_only 1` in the regular_testing config. However if you browse the configuration in the GUI, there is no indication that this is a one-way test.

Therefore I think the GUI should at least show, even if not allow editing, all possible testing fields. Hiding them in an "advanced" tab is fine by me.

**Comment by candlerb** [comment]
Also would like to see an indication of the `added_by_mesh   1` flag - no need to edit this one though!

**Comment by apertome** [comment]
I think these are good suggestions, thanks, Brian! We will try to incorporate them in 3.6.

**Comment by lisaens** [comment]
I've added 'omit_interval' to the throughput test config form.

**Comment by lisaens** [comment]
I've added a "Direction" dropdown to the throughput test form. It is interpreted to set the send_only and receive_only parameters.  (so far these changes are just in my branches)

**Comment by lisaens** [comment]
Put in a pull request
