### ISSUE TITLE
Remove NDT/NPAD from Toolkit GUI

### ISSUE THREAD

**Issue by apertome** [perfsonar/toolkit#221]
From @bltierney: 

> I found one more minor thing. https://host/toolkit/auth/admin/services.cgi on the toolkit still has checkbox for NDT and NPAD.

- [x] Remove NDT from services.cgi
- [x] Remove NPAD from services.cgi
- [x] Check to make sure NDT has been removed from the services list on the home page
- [x] Check to make sure NPAD has been removed from the services list on the home page
- [x] Grep for other instances of NDT/NPAD in the Toolkit

**Comment by apertome** [comment]
I removed *most* references to NDT and NPAD; a few remain

**Comment by apertome** [comment]
I removed the NDT/NPAD part from the auto-updates statement on the Toolkit; the rest of the cleanup can wait until 4.0.1.

**Comment by apertome** [comment]
PRs created in 
#261 
perfsonar/perl-shared#40

I could use some help testing that this doesn't break anything. Otherwise, it's done.

**Comment by arlake228** [comment]
The pull requests have been merged, can we close this?
