### ISSUE TITLE
Correct redirection of / to /toolkit

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/toolkit#223]
Seeing these in the server's error log:
```
[Tue Apr 04 17:57:51 2017] [warn] [client 131.188.81.85] incomplete redirection target of '/toolkit/' for URI '/' modified to 'https://131.188.81.85/toolkit/'
```
Should probably adjust the redirect in the HTTP config so the server doesn't squawk about it.

Slightly related to #103.

**Comment by arlake228** [comment]
That message only gets thrown in the logs on Apache 2.2 (i.e. CentOS 6). This is somewhat painful to fix if you want to capture all the various host configs we have to support and other methods seem to behave strange if you don't have things like a fully-qualified domain or if you want to preserve the given host address in the URL. Given that CentOS 6 is getting dropped, what we have is probably the cleanest way to do this.
