### ISSUE TITLE
Wrong count of tests per type on test configuration page

### ISSUE THREAD

**Issue by tonin** [perfsonar/toolkit#225]
In the admin section of the toolkit GUI, on the page to configure tests, the count of tests per host and per type is wrong.  See attached picture from the QALAB host where the table displays **1 test** of type throughput where there are actually 3 different tests configured by the mesh.

Tested on FF 52.0.2 on OSX if that matters.

<img width="820" alt="scheduled-tests" src="https://cloud.githubusercontent.com/assets/484879/24730604/132b11f4-1a54-11e7-8b64-518113692ab8.png">

**Comment by apertome** [comment]
Fixed
