### ISSUE TITLE
userlist: reliably crash browser (Firefox ESR 52.0.2 32bit)

### ISSUE THREAD

**Issue by igarny** [perfsonar/toolkit#226]
From: Charley Kneifel [charley.kneifel@duke.edu]
Sent: 08 April 2017 13:52
To: Garnizov, Ivan (RRZE); Andrew Lake; perfsonar-user@internet2.edu
Subject: Re: [perfsonar-user] perfSONAR 4.0rc3 now available for testing!

Hello Ivan,

I am able to reliably crash my browser (Firefox ESR 52.0.2 32bit) by:

Selecting test results (click on details)
In the new tab/window that pops up click on the blue Tput (TCP) selector to remove that data from the graph
click on the blue Tput (TCP) to add that data back to the graph - my browser will hang.

It does not happen if I do the same thing with any of the other data elements selectors (Tput (UDP), Loss (UDP), ...)

Charley

**Comment by apertome** [comment]
So far I have been unable to reproduce this one. Need to find out if it's still happening.

**Comment by apertome** [comment]
I asked the user a while back whether this is still happening, and haven't heard anything back. Closing -- we can reopen if we discover there is an issue here.
