### ISSUE TITLE
pS GUI red on 4G RAM

### ISSUE THREAD

**Issue by igarny** [perfsonar/toolkit#227]
From: Charley Kneifel [charley.kneifel@duke.edu]
Sent: 05 April 2017 20:26
To: Garnizov, Ivan (RRZE); Andrew Lake; perfsonar-user@internet2.edu
Subject: RE: [perfsonar-user] perfSONAR 4.0rc3 now available for testing!

![psgui-red-on-4g](https://cloud.githubusercontent.com/assets/11942774/24862636/a7d0916a-1dfd-11e7-9b54-fa3e1d28aa6d.jpg)

**Comment by apertome** [comment]
The commit above should fix this. Feel free to reopen if the next toolkit release doesn't fix it.
