### ISSUE TITLE
disable NetworkManager?

### ISSUE THREAD

**Issue by bltierney** [perfsonar/toolkit#228]
NetworkManager is running on the Toolkit. Should it be disabled by default?

**Comment by arlake228** [comment]
Leaving open to make sure i test with an ISO once its in the repos, but should be fixed now.

**Comment by bltierney** [comment]
I wonder if "tuned" should be disabled too? Might it conflict with our hand tunings?

Not sure...

**Comment by arlake228** [comment]
Another good catch. That doesn't seem like something we want on the toolkit. Disabling it.

**Comment by arlake228** [comment]
tested, seemed to work.
