### ISSUE TITLE
More info in JSON of index.cgi

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#23]
_From @arlake228 on March 14, 2015 12:46_

Original [issue 1037](https://code.google.com/p/perfsonar-ps/issues/detail?id=1037) created by arlake228 on 2015-01-06T20:38:49.000Z:

On the USATLAS call Shawn asked if the following would be possible to add to the index.cgi JSON output:

1. The percentage of time that BWCTL tests are running as shown on the &quot;Configure Tests&quot; page. This would be useful so they can programmatically see if a change they made to the mesh has put a host &gt; 100% testing.

2. He was also curious if it was possible to display manually configured tests in the JSON. Right now its just the mesh URL. They want a way to programmatically see what should be running on host.

_Copied from original issue: perfsonar/project#1035_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=1037#c1) originally posted by arlake228 on 2015-01-29T00:26:36.000Z:


Here are a couple other things he explicitly asked for as well:

  - disk space,
  - interface errors, 
  - load, 
  - ntp sync status 

It would be best if this were configurable, and disk space and load off by default, as there might be security concerns with those.

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=1037#c2) originally posted by arlake228 on 2015-01-30T19:02:53.000Z:

New API in the new UI should capture the bits we want to add.

**Comment by apertome** [comment]
Many of these have been added already, i.e. disk space, load, ntp sync status.

Some have not been added. More will be available in 3.6 (i.e. regular testing config, although this will have a separate URL).

**Comment by tonin** [comment]
This ticket can probably be closed for 4.0 or reviewed if more things still need to be added.

**Comment by apertome** [comment]
Actually I believe these are all there, closing.
