### ISSUE TITLE
Additional HTTP security headers

### ISSUE THREAD

**Issue by tonin** [perfsonar/toolkit#239]
We should add useful HTTP security headers to improve protection against click jacking and XSS attacks.

Specific HTTP headers and policies we should consider are:
- **Strict-Transport-Security** (HSTS) with `max-age=31536000 ; includeSubDomains`
- **X-Frame-Options** with `DENY` or `SAMEORIGIN`
- **Content-Security-Policy** to restrict the origin of scripts or other files loaded through a page, that probably should be the apache SERVER_NAME (or similar) and the sites where we get JS libraries and other files if any.
- **X-XSS-Protection** with `1; mode=block`
- **X-Content-Type-Options** with `nosniff`

There is more information at https://www.owasp.org/index.php/OWASP_Secure_Headers_Project#tab=Headers

From GN4-SA2T1 report 2.2.20.

**Comment by arlake228** [comment]
Duplicates perfsonar/project#1106. Merging.

**Comment by tonin** [comment]
I think it is good we keep this open as we need to review this in multiple components.  Maybe we should open an issue in each component we need to make changes and have the toplevel  perfsonar/project#1106 group all those issues.

**Comment by arlake228** [comment]
Regardless, my read of this is it doesn't add any specifics. Is there a particular config change you are suggesting that affects one of the components  not in the project issue (presumably the toolkit gui since it is in this repo)? If so add it here otherwise we should close.

**Comment by tonin** [comment]
The report suggest setting those headers in all generated pages:
- **X-Frame-Options** with DENY or SAMEORIGIN
- **Content-Security-Policy** to restrict the origin of scripts or other files loaded through a page, that probably should be the apache SERVER_NAME (or similar) and the sites where we get JS libraries and other files if any.
- **X-XSS-Protection** with **1; mode=block**
- **X-Content-Type-Options** with **nosniff**

There is more information at https://www.owasp.org/index.php/OWASP_Secure_Headers_Project#tab=Headers

**Comment by tonin** [comment]
As correctly noted in #242 we should also consider HSTS configuration.  This is also part of the [OWASP Secure Headers Project recommendations](https://www.owasp.org/index.php/OWASP_Secure_Headers_Project#tab=Headers).

**Comment by apertome** [comment]
This can build off the work in:
 perfsonar/project#1106

**Comment by apertome** [comment]
This didn't happen in the sprint ending this morning so I'm moving to the next sprint. Also decreasing the time estimate as a lot of what we need to do we already did in perfsonar/project#1106

**Comment by apertome** [comment]
I don't believe there is any legitimate reason why anyone should need to embed the Toolkit GUI, so I set **X-Frame-Options** to `DENY`. 

Please let me know if you have feedback.
