### ISSUE TITLE
Improve collection of longitude/latitude

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#24]
_From @arlake228 on March 14, 2015 12:49_

Original [issue 1050](https://code.google.com/p/perfsonar-ps/issues/detail?id=1050) created by arlake228 on 2015-01-22T15:45:55.000Z:

Related to #&nbsp;997

At the moment there are a number of sites reporting false Long/Lat information, with the nodes shown in completely the wrong place in the world at http://stats.es.net/ServicesDirectory/

Examples of problem sites:

* ndt.wusm.wustl.edu: gives coordinates as 38,90 [almost certainly should be -90 not 90]
* ETS (192.206.115.18): gives coordinates as 1,1 [probably just dummy data to turn off the yellow status]

<b>Describe the enhancement:</b>

Ideas include:

1. Pre-fill an initial long/lat value based on GeoIP and/or zip code (at least for US sites)
2. Pop up Google Maps to allow the user to zoom in and move the pin
3. Warn if the entered long/lat is not within the boundary of the selected country and/or state
4. Should it be non-compulsory to add coordinates? (i.e. no data is better than bad data)
5. Accepting data entry in degrees-minutes-seconds may make it easier to get granularity better than 1 degree, as otherwise people may not be inclined to convert to decimal degrees
6. Display positive/negative as N/S and E/W explicitly.

As a one-off event it would be possible to auto-validate the existing data and send out an E-mail to the contact if it appears to be suspect.

_Copied from original issue: perfsonar/project#1048_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=1050#c1) originally posted by arlake228 on 2015-01-22T19:28:17.000Z:

There was another issue related to this (#&nbsp;772). Some of this code already exists in the Toolkit under:
perfSONAR/Shared/lib/perfSONAR_PS/Utils/GeoLookup.pm

It contains geocoding and reverse geocoding methods that access the Google API as well as a GeoIP method that accesses the freegeoip.net API (GeoWHOIS is currently not implemented due to the inherent difficulties parsing whois data). These could be incorporated into Toolkit Administration Information page to have automatic determination/validation of data entered and meet the requirements of ideas 1-4.

On a related note the Lookup-Service-WebUI (Lookup Service Directory) already performs many of these lookups to determine location information for hosts that do not have it registered in the sLS. It could conceivably be used to validate the location information of any records registered in the sLS. Right now it assumes the sLS data is the source of truth and will not overwrite any pre-existing data, which makes it easy for users to easily identify incorrect data such as the host in Antarctica.

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=1050#c2) originally posted by arlake228 on 2015-01-27T15:10:09.000Z:

&lt;empty&gt;

**Comment by apertome** [comment]
I'm using this perl library for another project, and it uses a local database to do GeoIP lookups:

https://metacpan.org/pod/Geo::IP

It's probably not perfect, but it's vastly more reliable than the method we're using now, and using a local database means GeoIP lookups can happen for hosts that don't have access to the public internet. I have not yet established how accurate the lookups are, but I doubt it's worse than what we're doing now. The perl library and data are both available through EPEL, as well.

**Comment by lisaens** [comment]
I used Geo::IP to get the lat and long from the IP (ipv4 or ipv6).
To do:  Add rpm for newer GeoIP version to Internet 2 repo
and fix hard-coded paths to database files.

**Comment by lisaens** [comment]
Added a unit test.
Discovered that the Lite City ipv6 database does not actually have city info in it. The latitudes and longitudes it returns are for the middle of the country. So I made the function return just the Country. On the Configuration page, this will result in no button/default lat/long for ipv6 addresses. 
We may want to use some other library or service to get the lat/long values.

**Comment by lisaens** [comment]
GeoLookup.pm changes are in branch shared-24.
The new unit test is in branch unit-tests.

**Comment by lisaens** [comment]
For ipv6 addresses, the function will use the country database to get the country code and name. 
Added IP addresses for a company in Switzerland to the unit test.

**Comment by lisaens** [comment]
This has been merged into the perl-shared master (branch shared-24), but the unit test branch, with the unit test for it, has not yet been merged.

**Comment by apertome** [comment]
Didn't we merge this at one point? Can we close this?
