### ISSUE TITLE
Apache version string in footer of apache generated pages

### ISSUE THREAD

**Issue by tonin** [perfsonar/toolkit#241]
To lower the attack surface of perfSONAR installations we should remove apache generated footers in file listing and auto-generated pages.

From GN4-SA2T1 report 2.2.13 and 2.2.14.

**Comment by apertome** [comment]
This is simply an Apache config change, but we should review best practices, figure out how to implement, test that there are no harmful side effects, and figure out how to package the change (it might be able to go into the existing Apache config or scripts).

**Comment by apertome** [comment]
I've updated the Toolkit Apache config to accomplish this (though CentOS 7 was already stripping the version numbers from the file index/error pages. We might want to review whether this is the right place for this change; it's in the Toolkit config but applies to all locations ("/"), but that means it will only happen if the Toolkit is installed -- do we care whether other components do this, too?

**Comment by arlake228** [comment]
We should do this pscheduler and esmond and maddash.

**Comment by mfeit-internet2** [comment]
See https://github.com/perfsonar/pscheduler/issues/447.

**Comment by apertome** [comment]
I opened issues in the other two projects that we said need to have this. Closing this issue since the Toolkit is done.
