### ISSUE TITLE
HSTS by default

### ISSUE THREAD

**Issue by bbockelm** [perfsonar/toolkit#242]
At our local site, we've been trying to make sure all our web infrastructure receives as best SSLLabs as possible.

One thing that appears missing in the default perfSonar config is HSTS:

https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security

This helps encourage browsers to always prefer HTTPS, even when they start on HTTP.

Could this be added to the out-of-the-box defaults?

**Comment by tonin** [comment]
Thank you for the suggestion, we will be considering this for our next release, along with other HTTP security policies.  See #239.
