### ISSUE TITLE
Use drop-in in Debian packages

### ISSUE THREAD

**Issue by tonin** [perfsonar/toolkit#243]
Now that we have https://github.com/perfsonar/pscheduler/issues/404 (thanks!) we can use it in place of the [systemenv patch](https://github.com/perfsonar/toolkit/blob/debian/jessie/debian/patches/debian-systemenv.diff) that we have (and potentially other places).

**Comment by vvidic** [comment]
Updated toolkit to use drup-in for meshconfig-agent-tasks.conf in configure_esmond.

**Comment by vvidic** [comment]
Other uses are in database management that we handle using dbconfig. Should we close this than?

**Comment by tonin** [comment]
Yes, this is all, closing.
