### ISSUE TITLE
Build additional tests for shared functions

### ISSUE THREAD

**Issue by apertome** [perfsonar/toolkit#245]
Build additional tests for shared functions used by the various webservices/dataservices

**Comment by apertome** [comment]
This is also a continuation of work in #244

**Comment by apertome** [comment]
- [ ] Integrate running the tests into Jenkins
- [ ] Determine what level of coverage we have
- [ ] Update the GeoIP tests, which are broken on Debian

**Comment by apertome** [comment]
I believe I've fixed the GeoIP unit tests @vvidic reported an issue with in #244. @vvidic can you review and let me know? By the way there's an additional build requirement now, the perl module Test::Deep. 

Thanks!

**Comment by vvidic** [comment]
Here are the failures I get for debian/wheezy branch now:
```
#   Failed test 'Country is correct'
#   at /tmp/buildd/perfsonar-toolkit-4.0.0.2+20170601051413/t/lib/perfSONAR_PS/NPToolkit/UnitTests/Util.pm line 125.
#          got: undef
#     expected: 'US'

#   Failed test 'Full country name is correct'
#   at /tmp/buildd/perfsonar-toolkit-4.0.0.2+20170601051413/t/lib/perfSONAR_PS/NPToolkit/UnitTests/Util.pm line 126.
#          got: undef
#     expected: 'United States'

#   Failed test 'Country is correct'
#   at /tmp/buildd/perfsonar-toolkit-4.0.0.2+20170601051413/t/lib/perfSONAR_PS/NPToolkit/UnitTests/Util.pm line 125.
#          got: undef
#     expected: 'US'

#   Failed test 'Full country name is correct'
#   at /tmp/buildd/perfsonar-toolkit-4.0.0.2+20170601051413/t/lib/perfSONAR_PS/NPToolkit/UnitTests/Util.pm line 126.
#          got: undef
#     expected: 'United States'

#   Failed test 'Country is correct'
#   at /tmp/buildd/perfsonar-toolkit-4.0.0.2+20170601051413/t/lib/perfSONAR_PS/NPToolkit/UnitTests/Util.pm line 125.
#          got: undef
#     expected: 'CH'

#   Failed test 'Full country name is correct'
#   at /tmp/buildd/perfsonar-toolkit-4.0.0.2+20170601051413/t/lib/perfSONAR_PS/NPToolkit/UnitTests/Util.pm line 126.
#          got: undef
#     expected: 'Switzerland'

#   Failed test 'Country is correct'
#   at /tmp/buildd/perfsonar-toolkit-4.0.0.2+20170601051413/t/lib/perfSONAR_PS/NPToolkit/UnitTests/Util.pm line 125.
#          got: undef
#     expected: 'CA'

#   Failed test 'Full country name is correct'
#   at /tmp/buildd/perfsonar-toolkit-4.0.0.2+20170601051413/t/lib/perfSONAR_PS/NPToolkit/UnitTests/Util.pm line 126.
#          got: undef
#     expected: 'Canada'
# Looks like you failed 8 tests of 36.
```

**Comment by vvidic** [comment]
For debian/jessie branch:
```
#   Failed test 'Country is correct'
#   at /tmp/buildd/perfsonar-toolkit-4.0.0.2+20170601050903/t/lib/perfSONAR_PS/NPToolkit/UnitTests/Util.pm line 125.
#          got: undef
#     expected: 'CH'

#   Failed test 'Full country name is correct'
#   at /tmp/buildd/perfsonar-toolkit-4.0.0.2+20170601050903/t/lib/perfSONAR_PS/NPToolkit/UnitTests/Util.pm line 126.
#          got: undef
#     expected: 'Switzerland'

#   Failed test 'Country is correct'
#   at /tmp/buildd/perfsonar-toolkit-4.0.0.2+20170601050903/t/lib/perfSONAR_PS/NPToolkit/UnitTests/Util.pm line 125.
#          got: undef
#     expected: 'CA'

#   Failed test 'Full country name is correct'
#   at /tmp/buildd/perfsonar-toolkit-4.0.0.2+20170601050903/t/lib/perfSONAR_PS/NPToolkit/UnitTests/Util.pm line 126.
#          got: undef
#     expected: 'Canada'

#   Failed test 'Country is correct'
#   at /tmp/buildd/perfsonar-toolkit-4.0.0.2+20170601050903/t/lib/perfSONAR_PS/NPToolkit/UnitTests/Util.pm line 125.
#          got: undef
#     expected: 'US'

#   Failed test 'Full country name is correct'
#   at /tmp/buildd/perfsonar-toolkit-4.0.0.2+20170601050903/t/lib/perfSONAR_PS/NPToolkit/UnitTests/Util.pm line 126.
#          got: undef
#     expected: 'United States'

#   Failed test 'Country is correct'
#   at /tmp/buildd/perfsonar-toolkit-4.0.0.2+20170601050903/t/lib/perfSONAR_PS/NPToolkit/UnitTests/Util.pm line 125.
#          got: undef
#     expected: 'US'

#   Failed test 'Full country name is correct'
#   at /tmp/buildd/perfsonar-toolkit-4.0.0.2+20170601050903/t/lib/perfSONAR_PS/NPToolkit/UnitTests/Util.pm line 126.
#          got: undef
#     expected: 'United States'
# Looks like you failed 8 tests of 36.
```

**Comment by apertome** [comment]
@vvidic Since you are only getting undef values, I wonder if either the GeoIP library or data are not installed -- or perhaps the path to the data files is not configured correctly.  Can you check this?

**Comment by apertome** [comment]
This is done, aside from figuring out the issue Valentin is seeing.

I also added unit tests for the host "get_services" method.

**Comment by vvidic** [comment]
On Thu, Jun 01, 2017 at 07:54:44AM -0700, Michael Johnson wrote:
> @vvidic Since you are only getting undef values, I wonder if either
> the GeoIP library or data are not installed -- or perhaps the path to
> the data files is not configured correctly.  Can you check this?

Yep, that fixes the issues on Debian/jessie.  However on Debian/wheezy
it now fails with:

PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0)" t/*.t
Can't locate object method "country_name_by_addr_v6" via package "Geo::IP" at /usr/share/perl5/perfSONAR_PS/Utils/GeoLookup.pm line 74.
# Looks like you planned 36 tests but ran 6.
# Looks like your test exited with 255 just after 6.
t/host-geoIPLookup.t ........ 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 30/36 subtests 

Maybe we can skip some tests if country_name_by_addr_v6 is not
available?

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by apertome** [comment]
I created a new issue for tracking this issue directly in the next spring #260 . Closing this issue.
