### ISSUE TITLE
pscheduler does not have permission to run traceroute -I (ICMP option)

### ISSUE THREAD

**Issue by bltierney** [perfsonar/toolkit#250]
#pscheduler task trace --dest albq-owamp.es.net --probe-type icmp --source lbl-owamp.es.net
 
.....

Run failed.  The following errors were reported:
By lbl-owamp.es.net:
    The specified type of tracerouting is allowed for superuser only

A couple options to fix this include:

toolkit install does:  chmod 4755 /bin/traceroute
add user pscheduler to group 'wheel'  (I think)

and others....

**Comment by mfeit-internet2** [comment]
The pScheduler traceroute tool plugin should install configuration for that in sudoers.d.  Need to check that it actually does and that the run method uses sudo when it needs to.  I know this was done with ping.

**Comment by mfeit-internet2** [comment]
Don't change the permissions on the executable; that causes security concerns.

**Comment by bltierney** [comment]
doing the same thing we do for ping makes sense.

**Comment by mfeit-internet2** [comment]
Fixed in pScheduler 1.0.1 branch via 66bac20
