### ISSUE TITLE
Remove default apache welcome page

### ISSUE THREAD

**Issue by tonin** [perfsonar/toolkit#253]
A default install of pscheduler (and any other of our package that uses apache), without the toolkit package, displays the apache standard welcome page at the root URL.  This is both for CentOS and Debian installs.

Following recommendations from the security report, we should probably remove this page or put a redirect to some other place.

After discussion we decided it is better to put such a configuration in the toolkit-security package if anywhere.  We don't want to disturb the apache configuration too much, the node admin will decide if (s)he wants to install the toolkit-security package or not.

**Comment by arlake228** [comment]
I updated the perfsonar-toolkit security package to do this. See commit 11fdd92bdc3aea268d47628898bf113f6ddc905f. It also pulls the apache SSL config and the removal of Apache versions into this package. Appears to work as expected on CentOS. 

The Debian package will need to be updated to call the new script and drop in the new apache config to do so. Handing to @vvidic and @tonin to do so.

**Comment by vvidic** [comment]
What should we display on / instead of the default page? Shouldn't there be a redirect to /toolkit/ already?

**Comment by vvidic** [comment]
Apache changes integrated on the Debian side too.
