### ISSUE TITLE
show details off NTP sync on toolkit homepage

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#26]
_From @arlake228 on March 14, 2015 12:51_

Original [issue 1062](https://code.google.com/p/perfsonar-ps/issues/detail?id=1062) created by arlake228 on 2015-01-29T00:44:18.000Z:

Currently we have this:
&quot;NTP Status	  Synced&quot;

It would be good to be able to click on that, and get the output from 'ntpdc -p', to know who the host is syncing with, and how accurate the sync is.

_Copied from original issue: perfsonar/project#1060_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=1062#c1) originally posted by arlake228 on 2015-01-29T16:31:51.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=1062#c2) originally posted by arlake228 on 2015-01-30T19:11:12.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
is this still 3.5?

**Comment by apertome** [comment]
Unclear at the moment, most likely not but if there is a strong need we might be able to fit it in.

**Comment by arlake228** [comment]
Fixed in c4f3a0ad3eeb89bd7dac930916594fb271cba356

**Comment by apertome** [comment]
The backend support is there for this now, working on the frontend.

**Comment by apertome** [comment]
We may be able to squeeze this in for 3.5 since the backend support is already there. not certain just yet.

**Comment by apertome** [comment]
Done
