### ISSUE TITLE
toolkit services.cgi needs to be updated

### ISSUE THREAD

**Issue by bltierney** [perfsonar/toolkit#263]
Currently https://hostname/toolkit/auth/admin/services.cgi has just 2 services to configure: bwctl and owamp, and both appear to be on by default. Since bwctl is discouraged, this is pretty confusing.

At a minimum, I suggest adding something like:
"Note: bwctl is only for backwards compatibility with pre 4.0 perfSONAR".

and the page should also say something like:

"Also note that running latency and throughput tests on the same NIC is strongly discouraged"

But better yet, this page would configure different pscheduler limits for 'latency testers' vs 'throughput testers'

Not sure if this has already be discussed....

**Comment by arlake228** [comment]
This page probably just needs to go away entirely in 4.1 and is what this issue should track. It will be only one checkbox, OWAMP,  and honestly its just silly at that point. 

Even the applying limits thing won't quite work since latency tests  is a single participant test (i.e. its not going to ask pscheduler if it can run a latency test). You could maybe do something for throughput but at that point i'd argue this issue becomes #181

**Comment by apertome** [comment]
I agree that the services page is of limited utility, and we should get rid of it.

**Comment by bltierney** [comment]
+1
and probably ASAP.

**Comment by vvidic** [comment]
Please review the two pull requests that drop the services admin page.

**Comment by apertome** [comment]
@vvidic These changes look good, and test fine on CentOS 7. I'd say go ahead and merge them.

We will also have to update the docs to reflect this change; not sure who the best person to do that is -- what are your thoughts?

**Comment by vvidic** [comment]
On Fri, Sep 01, 2017 at 07:16:26AM -0700, Michael Johnson wrote:
> @vvidic These changes look good, and test fine on CentOS 7. I'd say go
> ahead and merge them.

Ok, clicked the merge just now.

> We will also have to update the docs to reflect this change; not sure
> who the best person to do that is -- what are your thoughts?

I can update the docs repo if that is what you ment here and maybe we
can ask Szymon to review it.  Not sure if there are some screenshots
of the toolkit web that need to be updated too?

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by tonin** [comment]
I created https://github.com/perfsonar/docs/issues/99 to follow up on the documentation part of this.  @vvidic feel free to make any change you see fit.
