### ISSUE TITLE
Integrate pScheduler's Built-In Backup

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/toolkit#264]
https://github.com/perfsonar/pscheduler/issues/170 added one-step backup and restore to pScheduler.  Integrate this with the toolkit.

To create a backup:  `pscheduler backup > path-to-backup-file`

To restore from a backup: `pscheduler-restore path-to-backup-file`.  The backup file can be `-` to read from standard input.  If standard output is a TTY, progress messages will be printed; redirect to `/dev/null` to force it to be quiet.

**Comment by mfeit-internet2** [comment]
Apparently this is Valentin's bailiwick.

**Comment by vvidic** [comment]
Please review pull request #266
