### ISSUE TITLE
Test descriptions and accented chars / UTF-8

### ISSUE THREAD

**Issue by tonin** [perfsonar/toolkit#265]
Different but wrong behaviour on the different platforms.

On Ubuntu 14, when I input "GÉANT MP" in a test name or test member description, the toolkit gui cannot save the new test configuration and replies to the user with "Error - Couldn't save Regular Testing configuration"

On CentOS7 and Debian 8, for the same input, I can save the test configuration, but further editing of the same test returns badly decoded UTF-8 chars like "GÃÂANT" instead of "GÉANT".

**Comment by vvidic** [comment]
Can you test the following patch on your hosts: https://github.com/perfsonar/perl-shared/commit/62ec521c15538ff9a1e94abe4c0045b45404af4a

**Comment by vvidic** [comment]
Another patch required for loading UTF-8 data: https://github.com/perfsonar/perl-shared/compare/tests-utf8

**Comment by apertome** [comment]
This still doesn't work for me on CentOS 7 at least. Trying to save with accented characters I get this message:

`AH01215: [Mon Jul 10 20:20:11 2017] regular_testing.cgi: malformed UTF-8 character in JSON string, at character offset 1081 (before "\\x{fffd}t","port":nu...") at /usr/share/perl5/vendor_perl/JSON.pm line 171., referer: https://perfsonar-dev8.grnoc.iu.edu/toolkit/auth/admin/tests.cgi`

**Comment by tonin** [comment]
Exact same error for me on Ubuntu 14 following the 2 file changes from the mentioned patch.

**Comment by tonin** [comment]
Saving the tests is working on my Ubuntu 14 host, but going back to the page there are errors at loading:
```
[Tue Jul 11 18:54:34 2017] regular_testing.cgi: utf8 "\xC9" does not map to Unicode at /usr/share/perl5/perfSONAR_PS/RegularTesting/Utils/ConfigFile.pm line 50.
[Tue Jul 11 18:54:34 2017] regular_testing.cgi: utf8 "\xE9" does not map to Unicode at /usr/share/perl5/perfSONAR_PS/RegularTesting/Utils/ConfigFile.pm line 112, <FILE> line 33.
```

**Comment by vvidic** [comment]
On Tue, Jul 11, 2017 at 09:55:38AM -0700, Antoine Delvaux wrote:
> Saving the tests is working on my Ubuntu 14 host, but going back to the page there are errors at loading:
> ```
> [Tue Jul 11 18:54:34 2017] regular_testing.cgi: utf8 "\xC9" does not map to Unicode at /usr/share/perl5/perfSONAR_PS/RegularTesting/Utils/ConfigFile.pm line 50.
> [Tue Jul 11 18:54:34 2017] regular_testing.cgi: utf8 "\xE9" does not map to Unicode at /usr/share/perl5/perfSONAR_PS/RegularTesting/Utils/ConfigFile.pm line 112, <FILE> line 33.
> ```

Does the tasks.conf file look good after the save or is it messed up?

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by tonin** [comment]
`meshconfig-agent-tasks.conf` is looking good, some extracts:
```
    <target>
        description   GÉANT Athens
```
```
<test>
    description   RTT éà
```

**Comment by tonin** [comment]
But it's actually not good, because file encoding is `latin1` and not `utf8`.  I guess we must set encoding right at the time of writing too.

**Comment by tonin** [comment]
Changing the `open` call at line 149 in `RegularTesting/Utils/ConfigFile.pm` makes things working right:

```
    unless (open(FILE, ">:encoding(UTF-8)", $file)) {
```

@vvidic can you submit the full PR?

**Comment by vvidic** [comment]
On Tue, Jul 11, 2017 at 10:56:39AM -0700, Antoine Delvaux wrote:
> Changing the `open` call at line 149 in `RegularTesting/Utils/ConfigFile.pm` makes things working right:
> 
> ```
>     unless (open(FILE, ">:encoding(UTF-8)", $file)) {
> ```
> 
> @vvidic can you submit the full PR?

Yep, but now its broken on stretch again, so we need to find
something that works on all 7 OS releases we have now.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by vvidic** [comment]
Updated the two branches so you can check again:

https://github.com/perfsonar/perl-shared/compare/tests-utf8
https://github.com/perfsonar/mesh-config/compare/tests-utf8

I did test all the Debian/Ubuntu and CentOS versions, but please try as it seems to be sensitive to the version of JSON and RPC::XML used so it can break in various combinations.

Please also test the UTF8 input in Admin info page, it seems to be broken at least on Ubuntu 14/trusty.

**Comment by vvidic** [comment]
Also don't think we need to force this for 4.0.1 release, as the change tends to influence/break various components. If pscheduler uses test names it might need to be updated for UTF8 too.

**Comment by apertome** [comment]
I think we agreed this is not a 4.0.1 task, so I'm moving it to 4.1.

**Comment by vvidic** [comment]
Right, please test and merge after 4.0.1 release.

**Comment by vvidic** [comment]
Please test and merge UTF8 changes now.

**Comment by arlake228** [comment]
I think Michael is out this week. I went ahead and did the test and merge on both.  RPMs built and should be hitting the testbed over the next few hours.

**Comment by vvidic** [comment]
Changes merged, guess it can be closed now.

**Comment by tonin** [comment]
Sorry to test it a bit late, but this still doesn't work properly on Ubuntu 14.  :(  I still get this error with the current code if I use UTF-8 chars in the test name/description or the host description:

```
[Mon Aug 28 17:50:35 2017] regular_testing.cgi: malformed UTF-8 character in JSON string, at character offset 6249 (before "\x{fffd} ici","type"...") at /usr/share/perl5/JSON.pm line 171.
```

However, when I change the line 106 in [perfSONAR_PS/NPToolkit/DataService/RegularTesting.pm](https://github.com/perfsonar/perl-shared/blob/master/lib/perfSONAR_PS/NPToolkit/DataService/RegularTesting.pm#L106) to what is below (removing version check), it is working fine:
```
    utf8::encode($json_text);
```

Ubuntu 14 is running `libjson-perl` `Version: 2.61-1`, like on Jessie.  But apparently it behaves differently.  Or should it be another lib version that should be checked?

**Comment by tonin** [comment]
I think that the key is not the libjson-perl or other JSON related lib, but perl version.  It is 5.18 in Ubuntu 14 and 5.20 in Debian 8.  perl 5.20 has improved UTF8 support overall.

**Comment by tonin** [comment]
https://github.com/perfsonar/perl-shared/pull/42/files is solving this for me on U14 and D8.  Probably needs more testing.

**Comment by tonin** [comment]
Working fine on D9 too.

**Comment by vvidic** [comment]
Changes merged, so closing again :)

**Comment by apertome** [comment]
I just tested this on my CentOS 7 host, and it works great there. Thanks for figuring this one out!
