### ISSUE TITLE
txdrop vs rxdrops mismatch in JSON summary

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#276]
From Shawn McKee:

```
I have been looking at a WLCG perfSONAR in Pakistan and found a possible bug.
Host is http://ps.ncp.edu.pk/toolkit/

See attached screen captures.

Looking at the interface states for 'eth1' from the toolkit web gui I see txdrops at 14422

However, looking at the JSON summary info, I don't see txdrops but instead see rxdrops (14498, a slightly different value).   Which is right?
```

**Comment by apertome** [comment]
First of all, the JSON stats were/are correct.

This turned out to be kind of odd, it wasn't a bug in any logic or something, but some CSS was improperly applied, causing the "transmitted" and "received" column labels to be swapped. I fixed the style issues and this should be good to go.
