### ISSUE TITLE
backup and restore fail if use slightly different versions

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#279]
From Mark:

> I think I’ve figured this out:
>  
> Embedded in Shawn’s backup is the new internal-to-pScheduler backup.  The production code doesn’t have that; it uses a database dump initiated by running pg_dump.  That means the backup was generated by a nightly or staging package.  The new system will have to be switched to at least staging for the database to be restorable.  The old version of the restore script didn’t find the database dump it would have written so it did nothing.
>  
> Dan:  Before 4.0.2 hits the streets, we’re going to need to restore the old code, add a check to figure out whether the backup has the old- or new-style backup and act accordingly.  The new-style backup has more than just the database and is laid out differently.

Technically we tell people they need to be on the same version when they migrate. I will take a look though and if it's easy we'll be a bit more forgiving.

**Comment by mfeit-internet2** [comment]
This should get you there:

```
if fgrep -qx -- '-- PostgreSQL database dump' /path/to/backup/file
then
    # Do old-style restore
else
    # Do pScheduler built-in restore
fi

```
