### ISSUE TITLE
oppd daemon with port assignment is not listed and checked as a service

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#28]
_From @arlake228 on March 14, 2015 12:52_

Original [issue 1074](https://code.google.com/p/perfsonar-ps/issues/detail?id=1074) created by arlake228 on 2015-02-10T14:51:10.000Z:

<b>What steps will reproduce the problem?</b>

1. http://psb01.pic.es/toolkit/?format=json or other pS 3.4 that has the oppd daemon
2. The daemon is accessible on on the 8090 port
3. But is not tested and listed on the json output

<b>What is the expected output? What do you see instead?</b>

service availability and configuration to appear on the json status report

_Copied from original issue: perfsonar/project#1072_

**Comment by apertome** [comment]
This has not been implemented yet as we are shooting for feature parity first. Setting to 3.6 for now.

**Comment by tonin** [comment]
OPPD will get retired and this is not needed anymore.
