### ISSUE TITLE
Make the LS activehosts URL configurable

### ISSUE THREAD

**Issue by tonin** [perfsonar/toolkit#281]
The toolkit WEBGUI is currently fetching the global list of LS from http://ps1.es.net:8096/lookup/activehosts.json which is hardcoded in the LS libraries.  It would be good to have this URL configurable in `web_admin.conf` so to ease firewall or proxy issues workaround but also maybe when people deploy their own LS and want to maintain their own list of LS.

Also, the firewall and ports information on http://docs.perfsonar.net/manage_security.html doesn't list port 8096 nor makes any difference in ingress and egress filtering on the firewall.  Maybe we should mention that the list of ports need to be open for both incoming and outgoing packets and add 8096 in the port list?

**Comment by apertome** [comment]
The `activehosts.json` URL may be hard-coded in the perl libraries and CGIS, and/or the Javascript libraries. Part of this task is to find instances where the URL is hard-coded and change them to use the configured value.
