### ISSUE TITLE
perfsonar-configure_nic_parameters: fails to set coalesce parameters

### ISSUE THREAD

**Issue by vvidic** [perfsonar/toolkit#297]
As reported by users the following fails with `igb` network driver:

    /sbin/ethtool -C eth0 rx-frames 1
    Cannot set device coalesce parameters: Unknown error 524 (ENOTSUPP)

With the `tg3` driver a similar problem exists setting `rx-usecs`:

    /sbin/ethtool -C eth0 rx-usecs 0

**Comment by vvidic** [comment]
Do we want to check the driver type and update the parameters used or maybe just warn if setting the values fails?

**Comment by tonin** [comment]
I would do both, if possible.  If we know what are the correct parameters to use for a specific driver, then use it.  But at the same time, we should make sure that not being able to set those parameters result in a warning and doesn't prevent the init script from running and the package from installing.

The init script and package installation issue is probably Debian specific (tbc), but the usage of correct parameters depending on the driver are probably for any distro.

**Comment by vvidic** [comment]
On Mon, Jan 29, 2018 at 11:42:48AM +0000, Antoine Delvaux wrote:
> I would do both, if possible.  If we know what are the correct
> parameters to use for a specific driver, then use it.  But at the same
> time, we should make sure that not being able to set those parameters
> result in a warning and doesn't prevent the init script from running
> and the package from installing.

Ok, I will try to prepare a patch like that.

> The init script and package installation issue is probably Debian
> specific (tbc), but the usage of correct parameters depending on the
> driver are probably for any distro.

The script might be failing on CentOS too, but the postinst there
does not check the exit status so the package installs without errors.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by vvidic** [comment]
First take on the updated script in the ethtool branch above. Please test on real hardware if possible.

**Comment by vvidic** [comment]
Users reported the pached version of the init script works on their hardware, so please review the PR #300 for RHEL.

**Comment by vvidic** [comment]
Could someone review this? One of the problem reports was for Ubuntu and the other for CentOS so we need the fix on both ends.
