### ISSUE TITLE
increase OWAMP defaults for tests and limits

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#3]
_From @arlake228 on March 14, 2015 12:53_

Original [issue 1085](https://code.google.com/p/perfsonar-ps/issues/detail?id=1085) created by arlake228 on 2015-03-10T16:11:46.000Z:

10pps for 50b packets was sufficient for legacy network testing.  Does it make sense to increase our defaults for regular testing?  e.g. 100ps (or 1000pps) with larger packets (500b?).  This could open up a large range of problems OWAMP is able to find.  

If the defaults are changed (or even if they aren't), the limits file for OWAMP should be modified to support a large 'bandwidth' number - this will allow people to default to 1000pps/10000pps testing with larger packets.  

_Copied from original issue: perfsonar/project#1083_

**Comment by arlake228** [comment]
Assigning to Brian. Do you have thoughts on a new set of new defaults?

**Comment by bltierney** [comment]
I think we should go with 1000pps, but not increase the packet size. But it
would be good to test it on a couple ESnet hosts first.

Can you deploy that in a couple places?


On Mon, May 18, 2015 at 8:17 AM, Andrew R. Lake <notifications@github.com>
wrote:

> Assigning to Brian. Do you have thoughts on a new set of new defaults?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/perfsonar/toolkit/issues/3#issuecomment-103094407>.
>



-- 
Brian Tierney, http://www.es.net/tierney
Energy Sciences Network (ESnet), Berkeley National Lab
http://fasterdata.es.net

**Comment by arlake228** [comment]
I just updated the Esnet mesh to do 1000pps in the ESnet Hub to Small DOE Site Border Packet Loss Testing mesh. We'll see how it does over the next few days.

**Comment by arlake228** [comment]
Testing over the weekend brought up an interesting point related to limits. The default limit for OWAMP tests is 1Mbps. 1Mbps is the limit on the sum total of all tests that match a particular limit class. Running at 1000pps works out to be 336Kbps got IPv4 (42 byte packet * 1000pps * 8bits in a byte = 336000). That means the third test pushes it over. We'll need to up the limit by at least a factor of 100 to match the corresponding rate. I am also wondering if we should add some additional wiggle room since 100Mbps is 297 tests and I think some of the bigger meshes are floating around this number.

**Comment by bltierney** [comment]
Hmm, I think some folks might complain about a steady-state 100Mbps of
owamp traffic by default on a heavily used perfSONAR node. (Its probably
fine on ESnet, but not for a default toolkit config).

Maybe we should just double it for now (to 200pps)?

Jason/Shawn/Eli: What do you think?


On Mon, Jun 8, 2015 at 8:15 AM, Andrew R. Lake <notifications@github.com>
wrote:

> Testing over the weekend brought up an interesting point related to
> limits. The default limit for OWAMP tests is 1Mbps. 1Mbps is the limit on
> the sum total of all tests that match a particular limit class. Running at
> 1000pps works out to be 336Kbps got IPv4 (42 byte packet * 1000pps * 8bits
> in a byte = 336000). That means the third test pushes it over. We'll need
> to up the limit by at least a factor of 100 to match the corresponding
> rate. I am also wondering if we should add some additional wiggle room
> since 100Mbps is 297 tests and I think some of the bigger meshes are
> floating around this number.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/perfsonar/toolkit/issues/3#issuecomment-110034767>.
>



-- 
Brian Tierney, http://www.es.net/tierney
Energy Sciences Network (ESnet), Berkeley National Lab
http://fasterdata.es.net

**Comment by arlake228** [comment]
Just to point out, changing it to 200pps by default would increase it by a factor of 20. The current default is 10pps.

**Comment by bltierney** [comment]
Ah, right. I meant just to double the current.

what is the total bW be for 100pps x 500 tests?

Maybe thats OK?

On Mon, Jun 8, 2015 at 8:36 AM, Andrew R. Lake <notifications@github.com>
wrote:

> Just to point out, changing it to 200pps by default would increase it by a
> factor of 20. The current default is 10pps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/perfsonar/toolkit/issues/3#issuecomment-110046640>.
>



-- 
Brian Tierney, http://www.es.net/tierney
Energy Sciences Network (ESnet), Berkeley National Lab
http://fasterdata.es.net

**Comment by arlake228** [comment]
100pps is 33.6Kbps per test so 500 would be 16.8Mbps. We could probably just make the limit an even 20Mbps in that case.

**Comment by bltierney** [comment]
This seems reasonable to me.



On Mon, Jun 8, 2015 at 8:43 AM, Andrew R. Lake <notifications@github.com>
wrote:

> 100pps is 33.6Kbps per test so 500 would be 16.8Mbps. We could probably
> just make the limit an even 20Mbps in that case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/perfsonar/toolkit/issues/3#issuecomment-110049129>.
>



-- 
Brian Tierney, http://www.es.net/tierney
Energy Sciences Network (ESnet), Berkeley National Lab
http://fasterdata.es.net
