### ISSUE TITLE
Update administrative info page with GDPR notice

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#304]
Add a GDPR notice and checkbox to accept it to the Toolkit GUI administrative info page.

**Comment by apertome** [comment]
Where are we going to get the content for this?

**Comment by tonin** [comment]
I'll provide the content.

**Comment by tonin** [comment]
Here is a quick draft/sketch of how I would see the notice text added to the toolkit Admin Web UI, along with a check box.  And the Save button would be greyed out, unless the box is ticked.  The last sentence of the text, or just the Privacy Notice words, can be a link to https://www.perfsonar.net/about/privacy-policy/ and we can also add this Privacy Notice mention and link in the Resources menu on the right.

![pswebadmin-gdpr-4](https://user-images.githubusercontent.com/484879/40509800-1dc95d7e-5f8a-11e8-82d6-257b9811263d.png)

**Comment by apertome** [comment]
This has been implemented and reviewed by Antoine, and is ready for packaging.
