### ISSUE TITLE
pS Testpoint install: chrony is being uninstalled in favor of ntp

### ISSUE THREAD

**Issue by igarny** [perfsonar/toolkit#308]
along with the inquiry here: #278
GEANT Operations have switched to using Chrony for the time synchronization on the servers.
It is even currently running on the production CentOS 6 servers and in order to get around the problem we are disabling the ntp daemon. This configuration is working already for about 2 months.

Would it be possible to possible to support Chrony  along with ntp daemon?

Here is the output on an Ubuntu16 perfsonar-testpoint install 
`perfsonar-testpoint (4.0.2 psmp/test perfsonar-jessie-release:perfsonar-jessie-release [all]) `

```
The following packages were automatically installed and are no longer required:
The following additional packages will be installed:
  libnet-ipv6addr-perl libnet-netmask-perl libnet-ntp-perl libnet-server-perl
  libyaml-syck-perl memcached netpbm ntp nuttcp owamp-client owamp-server
  python-memcache python-mock python-netaddr python-netifaces python-ntplib
  libyaml-perl ntp-doc apparmor poppler-utils fonts-japanese-mincho
The following packages will be REMOVED:
  chrony
The following NEW packages will be installed:
  libnet-ipv6addr-perl libnet-netmask-perl libnet-ntp-perl libnet-server-perl
  libyaml-syck-perl memcached netpbm ntp nuttcp owamp-client owamp-server
  python-memcache python-mock python-netaddr python-netifaces python-ntplib
The following packages will be upgraded:
```

**Comment by arlake228** [comment]
The reason we default to NTP is for the toolkit GUI since it needs to be updated to update chrony config files instead of NTP and right now, and that's not considered high priority at the moment. Since you are not using the toolkit GUI to configure NTP, you should be fine using chrony.

Closing since this also duplicates #278

**Comment by igarny** [comment]
Re opened since pS Testpoint install uninstalls `chrony` in favor of `ntp` package.
possibly both can be supported on non-toolkit deployments

**Comment by arlake228** [comment]
Also noting this has only been observed on Ubuntu16, other OSes would need to be checked.

**Comment by tonin** [comment]
In the Debian/Ubuntu packages, from the **perfsonar-testpoint** bundle package, the ntp dependency is registered in 2 places only, the other references shouldn't bring it:
 - bwctl and oppd have a direct dependency to `ntp`
 - owamp has a conditional dependency: `ntp | time-daemon`
 - libperfsonar-perl has a dependency to `libnet-ntp-perl` but that should not bring a dependency on ntp
 - python-pscheduler has a dependency to `python-ntplib` but that should not bring a dependency on ntp

OPPD is not installed by default anymore.  But the **perfsonar-testpoint** bundle is still dependant on **bwctl** which will bring the hard dependency to ntp.  This should go away with 4.1.

I'm not sure about the internals of **bwctl**, but does it rely on ntp itself or just on good time-sync?  Could we change the dependency to `ntp | time-daemon` like it is listed for owamp?

**Comment by tonin** [comment]
Issue moved to [perfsonar/bundles #15](https://github.com/perfsonar/bundles/issues/15) via [**ZenHub**](https://www.zenhub.com/)
