### ISSUE TITLE
Add option to do iperf single-ended test from toolkit GUI

### ISSUE THREAD

**Issue by tonin** [perfsonar/toolkit#312]
pscheduler now has the capability of doing iperf single-ended test towards devices not running pscheduler.  See https://github.com/perfsonar/pscheduler/issues/456

It would be useful to be able to setup such kind of tests from the toolkit GUI.  This should probably go into the **Advanced Parameters** section.

**Comment by apertome** [comment]
Need to add this flag to the GUI that sets this parameter:

`single-ended: true`

preferably as a sliding toggle

**Comment by apertome** [comment]
This has been implemented. Can someone (@tonin perhaps) test and make sure this is working correctly.

The GUI parts should be good, but I'm not sure about the interface with pscheduler, specifically:
https://github.com/perfsonar/perl-shared/commit/424068c1650e456b7445a1b24cfa44ff93118f4b#diff-c859b6223bbe9ec71f12fbde88a4d6e3R80

I am not sure what this part is supposed to look like.

Thanks!

**Comment by vvidic** [comment]
I don't get ``single-ended`` option in ``toolkit-webui.json`` after configuring the throughput test in the toolkit GUI. Are we still missing some part for this?

**Comment by arlake228** [comment]
I threw myself on the assignee list. The toolkit gui keeps things in the old meshconfig-agent-tasks.conf format and then converts them on save to psconfig. Right now psconfig does not know how to convert a meshconfig-agent-tasks.conf with the new single_ended option to single-ended. This will be very quick to add.

**Comment by arlake228** [comment]
This should be fixed now. Updating to the latest libperfsonar-psconfig-perl should do the trick. Did a quick local test and it showed-up in file.

**Comment by vvidic** [comment]
Looks good, single tests is created now and runs periodically with a remote iperf3 server.

**Comment by apertome** [comment]
OK great, in that case, I am closing this. Thanks, guys!
