### ISSUE TITLE
Error editing tests after update to Centos 7.5

### ISSUE THREAD

**Issue by akurov** [perfsonar/toolkit#313]
Hi,

After updating to CentOS 7.5 in tests configuration save don't work:

Error - Couldn't save Regular Testing configuration

Problem is in new package perl-HTTP-Daemon-6.01-7.el7.noarch, where change log say

* Mon Sep 18 2017 Petr Pisar <ppisar@redhat.com> - 6.01-7
- Accept undefined and empty-string LocalAddr as IO::Socket::INET does
  (bug #1413065)

* Tue Jan 17 2017 Petr Pisar <ppisar@redhat.com> - 6.01-6
- Support IPv6 (bug #1413065)

After downgrading to perl-HTTP-Daemon-6.01-5.el7.noarch from 7.4.1708 repo and restaring perfsonar-configdaemon.service save works again.

perfSONAR version 4.0.2.3-1.el7.centos

**Comment by arlake228** [comment]
We have a fix for this that will be out in the next day or so to fix this that will work with the newest version.
