### ISSUE TITLE
new machine won't globally register

### ISSUE THREAD

**Issue by siemsen** [perfsonar/toolkit#319]
lsregistrationdaemon.log says

2018/07/17 11:15:16 (1768) INFO> lsregistrationdaemon.pl:312 main:: - Configuration file change detected, refreshing records.
2018/07/17 11:15:21 (1768) ERROR> LookupService.pm:110 perfSONAR_PS::Utils::LookupService::discover_lookup_services - Problem retrieving http://ps1.es.net:8096/lookup/activehosts.json: 500 timeout
2018/07/17 11:15:21 (1768) WARN> lsregistrationdaemon.pl:144 main::__ANON__ - Warned: Use of uninitialized value $current_ls_instance in concatenation (.) or string at /usr/lib/perfsonar/bin/lsregistrationdaemon.pl line 257.
2018/07/17 11:15:21 (1768) INFO> lsregistrationdaemon.pl:257 main:: - Initial LS URL set to
2018/07/17 11:15:21 (1768) ERROR> lsregistrationdaemon.pl:301 main:: - Unable to determine ls_instance so not performing any operations

**Comment by siemsen** [comment]
PS the machine can ping ps1.es.net.

**Comment by arlake228** [comment]
Closing as it should be fixed in 4.1. See perfsonar/ls-registration-daemon#48. Can re-open if problem persists after update.
