### ISSUE TITLE
Problem with adding tests in perfSONAR 4.1.2

### ISSUE THREAD

**Issue by akurov** [perfsonar/toolkit#330]
Hi,

After I updated perfSONAR 4.0.2 to 4.1.2 on CentOS 7 tests configured with meshconfig/psconfig are running fine but tests that I added manually stopped running. 

There is error message If I try to remove tests:

> Error - Couldn't format pSConfig template file

After I cleaned files

> /etc/perfsonar/psconfig/pscheduler.d/toolkit-webui.json
> /var/lib/perfsonar/toolkit/gui-tasks.conf

I added new tests but if I try to delete them the same error appears.

**Comment by arlake228** [comment]
@akurov sorry this got lost in the shuffle, does this issue persist?

**Comment by akurov** [comment]
Yes, in perfSONAR version 4.1.3-1.el7 manually added test not running but I can run test with added host by running pscheduler in command line.

Other problem, not related with this bug: after update perl-Mojolicious-7.67-1.el7 to  perl-Mojolicious-7.94-1.el7 "Error loading test listing; measurement archive unreachable: " - is this problem known?

**Comment by arlake228** [comment]
Can you send me the address of your host assuming it is publicly accessible?

**Comment by akurov** [comment]
I sent hosts addresses on your email address.

**Comment by arlake228** [comment]
Closing as I am pretty sure this was a result of a Mojolicious update we had to do a special release for around the time this was reported.
