### ISSUE TITLE
Verify the correctness and usability of external Traceroute Visualization

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/toolkit#337]
Toolkit GUI provides links to a few external tool. One of them under URL http://www-wanmon.slac.stanford.edu/cgi-wrap/reflector.cgi?function=vtrace seems to be not working. I'm not sure the reason and if it is permanent. Is this the tool we still want to include in GUI?

The error is:
Error Code 480 reported by cgi-wrap
The WWW utility on www-wanmon.slac.stanford.edu:80 that you are refering to from your WWW browser (Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0) on called (using the GET method) a Common Gateway Interface (revision CGI/1.1) script command wrapper, which reports the following error
CGI-WRAP: reflector.cgi function=vtrace not validated by Rules list.

See SLAC's CGI Script Security Wrapper for more information on cgi-wrap.
[ SLAC Home Page | Feedback ]
Les Cottrell

I marked it a bug (because this is not working) but could be an enhancement (to remove this URL)

**Comment by arlake228** [comment]
I "fixed" this by removing the link. SLAC controls this and so far it has not been fixed. We can revisit if this gets restored.
