### ISSUE TITLE
Administrative info only accepts ASCII

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#34]
From Rade:

I've installed toolkit 3.4.2 on a VM. When I tried to enter my name, Serbian letters and all, I would get "Rade MartinoviÄ‡" after closing Host Info dialog. Then on clicking "Save" I would get:

Problem saving configuration: Problem saving administrative information
at the page top, which is not very descriptive.

When I converted to ASCII only characters, "Save" would work

**Comment by arlake228** [comment]
Delegated from perfsonar/project#1086

**Comment by apertome** [comment]
I was hoping that moving to a webservice would fix this, but it appears to be a problem with the underlying library. Probably around here:
https://github.com/perfsonar/perl-shared/blob/master/lib/perfSONAR_PS/NPToolkit/Config/AdministrativeInfo.pm#L68

**Comment by sowmyab** [comment]
Initial testing shows the problem to be with the RPC::XML library. I don't think it is a good idea to change a library that is used at several places in the toolkit without testing it properly. So, my suggestion is to push it to next release.

**Comment by arlake228** [comment]
Agreed, moved.

**Comment by vvidic** [comment]
I have a UTF-8 patch that seems to fix this (at least on Debian). Do you want me to send it here for review or commit it to the repo so you can check on RHEL too?

**Comment by mfeit-internet2** [comment]
@vvidic:  Creating a pull request will get it reviewed and part of the shipped code with less hassle and potential for errors.

**Comment by vvidic** [comment]
Ok, I just created 2 pull requests (in toolkit and perl-shared) for this issue.

**Comment by apertome** [comment]
I was going to suggest a pull request also, thanks, Valentin! I'll have a look at at it soon, most likely later today.

**Comment by apertome** [comment]
This doesn't solve the problem in my testing. However, I think it's a good start, so I merged the pull requests.

I neglected to mention that the Toolkit is using the LS Registration Daemon's config file (rather than the administrative_info file, which is redundant). So the UTF-8 fixes will have to happen in the LS Registration Daemon code as well. I tried to find the spot in that code, but I'm not very familiar with it. Maybe @sowmyab  can help with that part?

**Comment by sowmyab** [comment]
Here is the piece that modifies the LSRegistrationDaemon's config: http://github.com/perfsonar/perl-shared/blob/master/lib/perfSONAR_PS/NPToolkit/Config/LSRegistrationDaemon.pm

**Comment by vvidic** [comment]
There is a -UTF8 option for Config::General. I've created a new pull request in perl-shared so give it a try.

**Comment by apertome** [comment]
I made a couple others changes, but it seems to work now. It'd be great if someone could help me test it, with more of a real-world UTF-8 use case than what I've been trying. Thanks.

**Comment by tonin** [comment]
I have updated Debian packages in the snapshot repo with the latest corrections (both for Debian 7 & 8).

**Comment by vvidic** [comment]
I confirm it works for me on Debian now.

**Comment by apertome** [comment]
Everything seems to work. Closing.
