### ISSUE TITLE
Add paris-traceroute RPM to toolkit

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#37]
RPM at https://code.google.com/p/paris-traceroute/wiki/Installation#rpm-based_distributions_(Fedora,_RedHat_,_Centos,_etc.)

**Comment by arlake228** [comment]
Child issue of perfsonar/project#1089

**Comment by tonin** [comment]
Not too good to see this project still hosted on Google Code and not much activity on the mailing list/google group: https://groups.google.com/forum/?fromgroups#!forum/paris-traceroute

Would that mean we should consider copying it all over to github ourselves?

**Comment by arlake228** [comment]
I don't think we need to copy it. Shawn McKee is in touch with the developers and they've actually been relatively responsive when it comes to fixing bugs or giving us packages. They built the current set of RPMs on our request. If you need Debian packages or similar, I'd recommend giving that information to Shawn and having him pass it along.
