### ISSUE TITLE
Configurable link to Privacy Notice

### ISSUE THREAD

**Issue by tonin** [perfsonar/toolkit#373]
It would be nice to have a configurable link (and configurable text of the link) to a Privacy Notice on the main public toolkit page, for example in the right-hand menu.

By default, the link could be pointing to our [own Privacy Policy](https://www.perfsonar.net/about/privacy-policy/).

**Comment by tonin** [comment]
Thanks for this addition @bhavesh37 

However, I now have the unit tests failing with the new fields `pn_link` and `pn_text`.  After trying to fix that I noticed that these 2 added fields are inserted in the `lsregistrationdaemon.conf` file, although I wouldn't expect this information to be posted to the LS.

Wouldn't it be better for this information to be saved in the `web_admin.conf` file instead?  What do you think @apertome ?

**Comment by apertome** [comment]
I concur, thanks, antoine

**Comment by apertome** [comment]
Bhavesh is having another look at this. FWIW, I think I inadvertently told him to use `lsregistrationdaemon.conf`, so this is really my mistake.

@tonin Exactly which unit tests exactly are you referring to?

**Comment by tonin** [comment]
It is the toolkit unit tests that are failing, at least on Debian, with mention of the 2 new fields as extra data.

**Comment by apertome** [comment]
ok, thanks. Looks like Bhavesh is out today, I'll have a look a bit later in the day

**Comment by tonin** [comment]
For the record, here are the unit tests I see failing on the toolkit while building the Debian packages:
```
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0)" t/*.t
t/host-geoIPLookup.t ........ ok     
t/host-get_metadata.t ....... 1/3 
#   Failed test 'Metadata values are as expected'
#   at /build/perfsonar-toolkit-4.2.0~0/t/lib/perfSONAR_PS/NPToolkit/UnitTests/Util.pm line 121.
# Comparing hash keys of $data->{"config"}
# Extra: 'pn_link', 'pn_text'
# Looks like you failed 1 test of 3.
t/host-get_metadata.t ....... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests 
t/host-get_services.t ....... ok     
t/host-get_system_health.t .. ok     
t/host-update_metadata.t .... 1/23 
#   Failed test 'Metadata values are as expected'
#   at /build/perfsonar-toolkit-4.2.0~0/t/lib/perfSONAR_PS/NPToolkit/UnitTests/Util.pm line 121.
# Comparing hash keys of $data->{"config"}
# Extra: 'pn_link', 'pn_text'

#   Failed test 'Metadata values are as expected ( save_success: 0; restart_success: -1 )'
#   at /build/perfsonar-toolkit-4.2.0~0/t/lib/perfSONAR_PS/NPToolkit/UnitTests/Util.pm line 121.
# Comparing hash keys of $data->{"config"}
# Extra: 'pn_link', 'pn_text'

#   Failed test 'Metadata values are as expected ( save_success: 1; restart_success: 0 )'
#   at /build/perfsonar-toolkit-4.2.0~0/t/lib/perfSONAR_PS/NPToolkit/UnitTests/Util.pm line 121.
# Comparing hash keys of $data->{"config"}
# Extra: 'pn_link', 'pn_text'

#   Failed test 'Metadata values are as expected ( save_success: 1; restart_success: -1 )'
#   at /build/perfsonar-toolkit-4.2.0~0/t/lib/perfSONAR_PS/NPToolkit/UnitTests/Util.pm line 121.
# Comparing hash keys of $data->{"config"}
# Extra: 'pn_link', 'pn_text'
# Looks like you failed 4 tests of 23.
t/host-update_metadata.t .... Dubious, test returned 4 (wstat 1024, 0x400)
Failed 4/23 subtests 
t/test-delete_all_tests.t ... ok   
t/test-get_tests.t .......... ok       

Test Summary Report
-------------------
t/host-get_metadata.t     (Wstat: 256 Tests: 3 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
t/host-update_metadata.t  (Wstat: 1024 Tests: 23 Failed: 4)
  Failed tests:  3, 9, 15, 21
  Non-zero exit status: 4
Files=7, Tests=226,  9 wallclock secs ( 0.05 usr  0.01 sys +  6.33 cusr  0.56 csys =  6.95 CPU)
Result: FAIL
Failed 2/7 test programs. 5/226 subtests failed.
```

When I add `'pn_link' => undef, 'pn_text' => undef` in the `get_updated_metadata` and `get_original_metadata` subs from `t/host-update_metadata.t` and in `$expected_metadata` from `t/host-get_metadata.t` then everything's fine.

**Comment by bhavesh37** [comment]
https://github.com/perfsonar/toolkit/pull/383 is the new pull request that addresses this issue, tests did pass on perfsonar-dev9 after these changes

**Comment by apertome** [comment]
Antoine merged this the other day
