### ISSUE TITLE
add_pssudo_user should be smarter with bundle installation

### ISSUE THREAD

**Issue by tonin** [perfsonar/toolkit#375]
When installing pS through the bundles, a sudo user can already be existing.  The admin of the server might be interested in having this existing user being the **pssudo** user.  However, our `add_pssudo_user` script fails when one tries to add any existing user.

**Comment by vvidic** [comment]
Do you mean we should just add the user to the pssudo group if it already exists?

**Comment by vvidic** [comment]
Let me know if the PR works for you?

**Comment by tonin** [comment]
Working fine, thanks!
