### ISSUE TITLE
Add paris traceroute to config GUI

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#38]
We need to add paris-traceroute as an option in the configuration GUI so people can select it

**Comment by arlake228** [comment]
Child issue of perfsonar/project#1089

**Comment by arlake228** [comment]
Fixed on old GUI. Leaving open so we remember to add this option to new regular testing GUI

**Comment by apertome** [comment]
Changing to 3.6 for now. may get changed to 3.5.1.

**Comment by apertome** [comment]
Implemented in 3.5.1
