### ISSUE TITLE
Installing toolkit on Centos / Post installation issue

### ISSUE THREAD

**Issue by LucRoadRunner** [perfsonar/toolkit#395]
Installing : pscheduler-server-4.2.1-1.el7.noarch                                                                                                              469/565 
Created symlink from /etc/systemd/system/multi-user.target.wants/pscheduler-ticker.service to /usr/lib/systemd/system/pscheduler-ticker.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/pscheduler-runner.service to /usr/lib/systemd/system/pscheduler-runner.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/pscheduler-archiver.service to /usr/lib/systemd/system/pscheduler-archiver.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/pscheduler-scheduler.service to /usr/lib/systemd/system/pscheduler-scheduler.service.
Setting SELinux permissions (may take awhile)
Error getting active value for 
Boolean  is not defined
Error getting active value for 
Boolean  is not defined
Error getting active value for 
Boolean  is not defined
Created symlink from /etc/systemd/system/multi-user.target.wants/httpd.service to /usr/lib/systemd/system/httpd.service.

SELinux permissions not set properly. Acces to the Web server of the toolkit fails if SELinux is not set to permissive or disabled.

**Comment by tonin** [comment]
Issue moved to [perfsonar/pscheduler #955](https://github.com/perfsonar/pscheduler/issues/955) via [**ZenHub**](https://www.zenhub.com/)
