### ISSUE TITLE
Alternative View of Communities for pSPT Setup

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#4]
_From @arlake228 on March 14, 2015 5:57_

Original [issue 532](https://code.google.com/p/perfsonar-ps/issues/detail?id=532) created by arlake228 on 2011-05-04T09:39:59.000Z:

The &quot;word cloud&quot; of communities can be insufficient at times.  A user writes:

&quot;If I am a member of some group, like Los Nettos or MaineREN, which appear in the list, but do not appear benefit significantly from font-size promotion, then I will be forced to scan the list for pertinent groups, and if so then alphabetical order is the only tool I have left. (It appears to be in ASCII-order now, so you'd have to guess whether the community is capitalized or not.)

The word cloud is merely confusing to the eye, unless you want to join Internet2, LHC, USATLAS, ESNet, or perfSONAR-PS.

Someone reaching the point of choosing a community will want the community they want, and &quot;popularity&quot; is of no use in finding it. Somebody who joins LHC doesn't join it because its font is big, they join it because it's pertinent to their work.&quot;

_Copied from original issue: perfsonar/project#531_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=532#c1) originally posted by arlake228 on 2012-03-13T17:37:36.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=532#c2) originally posted by arlake228 on 2012-09-18T16:02:41.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Comment [#3](https://code.google.com/p/perfsonar-ps/issues/detail?id=532#c3) originally posted by arlake228 on 2014-07-14T22:41:38.000Z:

The word cloud really does not scale, and needs to go away.

**Comment by arlake228** [comment]
Comment [#4](https://code.google.com/p/perfsonar-ps/issues/detail?id=532#c4) originally posted by arlake228 on 2015-01-27T15:16:48.000Z:

&lt;empty&gt;

**Comment by apertome** [comment]
Communities will be displayed very differently in 3.5.

**Comment by apertome** [comment]
Word cloud is gone in 3.5, replaced with a selector widget
