### ISSUE TITLE
Update NTP server list

### ISSUE THREAD

**Issue by apertome** [perfsonar/toolkit#406]
We are finally in a situation where new installs sometimes have no functioning NTP servers, since our list is outdated. Need to update this.

**Comment by apertome** [comment]
Removed old, dead servers from the list, added some new ones, seems to work on the centos side. would like someone else to test it. Also not sure what, if anything, will have to be done for Debian

**Comment by tonin** [comment]
I reviewed and added a few more.  There's nothing specific to do for the Debian package, we're using the same `configure_ntpd` script.

**Comment by apertome** [comment]
@tonin I assume this has been confirmed fixed on the Debian side at this point?

**Comment by tonin** [comment]
Yes, working fine with the new servers list on Debian.  Closing.
