### ISSUE TITLE
Unexpected latency values in summary in toolkit GUI

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/toolkit#409]
Putting to issue something I was discussing with @apertome 

In one of my toolkits https://perfsonar.eenet.ee/toolkit/ when in the main page you look at summary results for tests towards 150.254.160.19 for the last 1 week outgoing latency shows a high value >25ms. See screenshot.
![obraz](https://user-images.githubusercontent.com/12281679/98345150-8e135b00-2014-11eb-86ef-54c801c2637e.png)
But when you go to detailed graph(https://perfsonar.eenet.ee/perfsonar-graphs/?source=193.40.132.142&dest=150.254.160.19&url=https%3A%2F%2Fperfsonar.eenet.ee%2Fesmond%2Fperfsonar%2Farchive%2F&timeframe=1w#start=1604047446&end=1604652246&summaryWindow=86400&timeframe=604800&timesel=1w&startDate=Fri%20Oct%2030%202020%2009%3A44%3A06%20GMT%2B0100&endDate=Fri%20Nov%2006%202020%2009%3A44%3A06%20GMT%2B0100) all latency values are much lower (less then 15ms) - there is no single value visible like this. This is very confusing and difficult to understand and interpret
![obraz](https://user-images.githubusercontent.com/12281679/98345228-ad11ed00-2014-11eb-8210-34168e8468a2.png)

So a few questions come:
- is this a bug in calculations in the front page?
- I think that because the two pages use the same time period they must show the same results - not different. Now I really don't know how to interpret it when a value is shown that doesn't exist in detailed view (btw I would rather expect opposite if you use some aggregation i.e. have more diversity in detailed view than in the front page)
- in any case it would be good and document in documentation (or faq) to know how the values presented for both metrics (bw and lat) are calculated i.e. is it showing some min/max/avg and from which results. Maybe also indicate this in GUI.

**Comment by apertome** [comment]
It turns out that the Toolkit table is using averages for all the values, when I use min for latency the values make much more sense.

It does some odd things with negative latency values, though. It's always a bit tricky to figure out how to handle them in a way that makes sense.

Example (note: this is my dev host but the URL points at the MA of the host you shared):
https://perfsonar-dev8.grnoc.iu.edu/toolkit/?url=https://perfsonar.eenet.ee/esmond/perfsonar/archive/

This example has some negative values (my same dev host, using its local MA):
 http://perfsonar-dev8.grnoc.iu.edu/toolkit/

We could show the min non-negative number, or min absolute value (but that seems a little misleading, possibly), or keep the actual min value we get, even if it is negative.

Thoughts?

**Comment by apertome** [comment]
I believe this is fixed and ready for 4.3.2 bugfix release, pending additional feedback from Szymon

**Comment by szymontrocha** [comment]
So which option you chose? Actual min value? Is the negative value also shown in the graph then to match the summary view?

**Comment by szymontrocha** [comment]
Still discussing it today a bit with Michael.

So we have the following choices (for the selected time period):
1. Minimum value (show also values below 0, can have minus sign)
2. Minimum positive value (show only values >=0, will never have minus sign)
3. Minimum absolute value (like artificial value, will never have minus sign)
4. Maximum positive value
I don't like 3 because it's artificial and you will not see such value in the graph
wrt 1 negative latency is cut from the graph so not ideal correlation between summary page and the graph (although shown in the tooltip)
From user perspective I think it's important to correlate the summary value with the detailed graph values. If the value is not there then it's misleading. So if you not showing negative then option 2 makes more sense.
I also tend to think that option 4 is somehow interesting. What am I interested in most when looking at latency? What worries me most? Minimal value or maximal? Maximal may indicate path change or some other issues. So from this perspective even maximal can be optimal.

Also a suggestion: whatever we finally choose you may consider a tooltip (not sure this is possible) when you hover over the column headers   in the main page i.e. over "THROUGHPUT" or "LATENCY (MS)" that will show "Average" or "Minimum positive" or something like this to explain to the user

**Comment by apertome** [comment]
I have changed it to minimum positive value. I think this makes more sense. If people want to do something more sophisticated, they can do it once the ELK options are in place

**Comment by szymontrocha** [comment]
Thanks Michael. Will you consider a tooltip or extended header name?

**Comment by apertome** [comment]
We're ready to tag this release, but we can add more details later. Followup in #411 .
