### ISSUE TITLE
Add support for setting host role and access policies to admin page

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#41]
The ls_registration daemon now supports the following fields is ls_registration_daemon.conf that should be set in the administrator interface:

1. "role" - This should be select that allows 0 or more of the following to be selected
  * nren
  * regional
  *  site-border
  * site-internal
  * science-dmz
  *  exchange-point
  * test-host
  *  default-path
  *  backup-path
2. "access_policy" - It can be exactly one of the following
 *  public
  * private
  * research-education
  * limited
3. "access_policy_notes" - This is human readable text that can optionally be added to help further describe the access policy
4. "is_virtual_machine" - Can be set to 0 or 1 depending on whether this is a VM
5. "tcp_max_achievable" - This is an integer in bits per second (bps) that indicates the maximum known bandwidth. This may significantly differ from the interface speed if the hardware is incapable of reaching theoretical maximums (as an example).

This is obviously for consideration post-3.5 RC1 when planning the admin interface future.

**Comment by apertome** [comment]
This is in the 3.5.1 codebase.
