### ISSUE TITLE
pS 5.0 Ubuntu 20: script bug perfsonar-configure_nic_parameters

### ISSUE THREAD

**Issue by igarny** [perfsonar/toolkit#432]
> grep  /sbin/ifquery    /etc/init.d/perfsonar-configure_nic_parameters
interfaces=$(/sbin/ifquery --all --list | grep -v -w lo)
interfaces="$interfaces $(/sbin/ifquery --allow hotplug --list)"

>ls /sbin/ifquery
ls: cannot access '/sbin/ifquery': No such file or directory

**Comment by tonin** [comment]
https://github.com/perfsonar/toolkit/commit/805c7e3726d614c4320e88fabfb0ffd408aff796 should provide a fix to this issue.

**Comment by igarny** [comment]
The testing on Ubuntu20 of the pS Toolkit 5.0.2 May24 on a VMWare server showed that the config script is able to configure
TXQUEUELEN, but not the Frame related parameters.
The issue is not related to the script, but to the hardware / driver.

The script has a section which recognizes certain type of drivers:
```
if [ "${RX_FRAMES-unset}" = "unset" ]; then
    DRIVER=$(ethtool -i $1 | sed -n 's/^driver: //p')
    case $DRIVER in
        igb) RX_FRAMES=;  RX_USECS=1;;
        tg3) RX_FRAMES=1; RX_USECS=1;;
          *) RX_FRAMES=1; RX_USECS=0;;
    esac
fi
```
I would suggest adding the vmware driver as an exemption of the general case:

```
root@r75:~# ethtool -i ens224 | grep driver
driver: vmxnet3
```

**Comment by tonin** [comment]
Do you mean the default `RX_FRAMES=1; RX_USECS=0;` is not good for the `vmxnet3` driver?  What would be the best setting for this driver?

**Comment by igarny** [comment]
The best setting should be 
RX_FRAMES=; RX_USECS=;
