### ISSUE TITLE
on Ipv6 i cant add host for tests in Toolkit, it says Couldnot save configuration file

### ISSUE THREAD

**Issue by Rezi1999** [perfsonar/toolkit#440]
i was working on installation of  PERFSONAR-TOOLKIT on ubuntu 20.04 with ipv6 only, I wanted to test the latency and bandwidth between the hosts, and for that I used perfsonar's public hosts with ipv6 only, but when adding the host, it said that I could not save the configuration file, attaching screenshot:

![toolkit_error](https://github.com/perfsonar/toolkit/assets/110170376/cc5ef17f-7ac7-4bc7-801d-5274e23d9fbf)

if you guys have any thoughts how to fix it, it would be helpful.

**Comment by tonin** [comment]
Thank you for the report @Rezi1999  Did you say that adding an `/etc/hosts` entry for the IPv6 localhost solved this issue?

**Comment by Rezi1999** [comment]
@tonin No, adding ipv6 localhost to /etc/hosts  fixed one of the elmond service errors (proxy localhost error),  because apache was proxying to localhost and on ubuntu 20 localhost didn't have ipv6, manually adding it fixed the problem. i think this is a bug on ubuntu 20.04, because i tested it installed couple ubuntu 20.04s and none of had ipv6 localhost entry by default.

**Comment by tonin** [comment]
@Rezi1999 Do you see some error in the different perfSONAR or Apache log files? Is the `perfsonar-configdaemon` running? Can you track anything down?

**Comment by laeti-tia** [comment]
Linked to https://github.com/perfsonar/toolkit/issues/448

**Comment by laeti-tia** [comment]
@Rezi1999 can you test that bug report with the latest changes and close the issue if it is solved?

**Comment by Rezi1999** [comment]
> @Rezi1999 can you test that bug report with the latest changes and close the issue if it is solved?

forgot to close the issue, this one already solved.
