### ISSUE TITLE
Opensearch/Logstash u/p environments not initialized properly

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/toolkit#446]
Reported by users but I also experienced it in Toolkit Ubuntu20 install. When applying workaround it works:

I was getting 503 errors when attempting to archive, similar to other users. My installation is perfsonar-toolkit on Ubuntu 20.

The /var/log/logstash/logstash.plain log was a continuous series of the service starting, erroring, and stopping. The error was:

Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:pscheduler, :exception=>"Java::JavaLang::IllegalStateException", :message=>"Unable to configure plugins: Cannot evaluate `${opensearch_output_host}`. Replacement variable `opensearch_output_host` is not defined in a Logstash secret store or an environment entry and there is no default value given."

The "opensearch_output_host" value is contained in /etc/perfsonar/logstash/logstash_sysconfig, which also contains opensearch_logstash_user and opensearch_logstash_password.

These variables are referenced in /usr/lib/perfsonar/logstash/pipeline/99-outputs.conf. If I replace the variables in 99-outputs.conf with the values in logstash_sysconfig and restart the logstash service, the error goes away and is replaced with a 401 error when attempting to contact OpenSearch at the given address (https://localhost:9200/).

If I then replace the user and password values in 99-outputs.conf with the OpenSearch login contained in /etc/perfsonar/opensearch/opensearch_login, then upon restart the logstash service works correctly and I have records displayed in the Test Results section of the web UI.

**Comment by szymontrocha** [comment]
This is now observed in 5.0.5 but I think this node was initially installed with one of the previous versions and than auto-upgraded. Not sure what was the case in the deployments reported by users -

**Comment by laeti-tia** [comment]
There might be leftovers from previous installations and upgrades that prevent the config file from being correct.  It also seems that OpenSearch installation scripts are prone to timeout and that a host without enough resources might run into this installation issue again.

**Comment by jvuleta** [comment]
My apologies for not replying earlier. Time out happens on machines with limited hardware, i. e. configuration close to minimal hardware requirements, when dependencies are downloaded. There isn't a specific line (archive) where script times out.

**Comment by jvuleta** [comment]
The final conclusion is: machine with appropriate hardware should be used.
