### ISSUE TITLE
iperf3 should not be listed as service on new gui

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#45]
Looking at the new GUI, I don;t think it makes sense to list iperf3 as a service. iperf3 is generally not running except for when a BWCTL test runs. I suspect it is there since we listed the version on the old GUI. I'd say remove it from that page entirely. One alternative suggestion would be to have a collapsable tab in the right menu that you can expand to list versions of various other software components installed. We could probably stick some other key software version in there if we go that approach (cassandra, and paris-traceroute come to mind, there are probably others)

**Comment by apertome** [comment]
It seems to me we should remove iperf from the services webservice, and maybe add a get_software method that returns a more detailed list of relevant software and versions

**Comment by apertome** [comment]
Removed iperf3 from the service list.
