### ISSUE TITLE
Changing Administravie information on toolkit interface issue 5.0.6

### ISSUE THREAD

**Issue by Rezi1999** [perfsonar/toolkit#450]
After updating Perfsonar from 5.0.5 to 5.0.6 changing Administrative Infromation goes to Internal Server Error:
![administrative](https://github.com/perfsonar/toolkit/assets/110170376/70bc5ab2-e4b2-42d9-bf66-fb75b5e2cb26)

This is apache2 logs:
`Can't call method "set_organization_name" on unblessed reference at /usr/share/perl5/perfSONAR_PS/NPToolkit/DataService/Host.pm line 180.`

**Comment by vrelk-net** [comment]
I didn't look at those logs, but I did  notice the registration service wasn't running. Looking at the logs for that indicated that `lsregistrationdaemon.conf` was missing. I did verify it was there when first setting up another VM, but later on while configuring PS, I started getting that error and noticed it had gone missing.
`touch /etc/perfsonar/lsregistrationdaemon.conf` fixed it for me.
