### ISSUE TITLE
Replace nscd with system-resolved

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#451]
We should replace nscd with systemd-resolved. nscd seems to be causing IPv6 issues and is generally deprecated. systemd-resolved is available on all supported OSes...and seems to even be installed and enabled by default on Ubuntu.

We should also disable nscd as part of this update as well.

**Comment by timchown** [comment]
This has not been resolved (sic) in 5.0.7.
Jisc and UK GridPP sites report nscd is still running after the update.
