### ISSUE TITLE
Create symlink to pscheduler log from /var/log/perfsonar/

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/toolkit#457]
In 4.x there was /var/log/perfsonar/pscheduler.log -> /var/log/pscheduler/pscheduler.log Now in 5.x it's gone (checking in Ubuntu 20 Toolkit install) and there is no symlink which was very handy. It would be nice to have it back

**Comment by laeti-tia** [comment]
It seems this link is a feature coming from our RPM not present in our Deb packages.

**Comment by szymontrocha** [comment]
As far as I see testing 5.1 toolkit with Ubuntu 20, there isn't such symlink too there.

**Comment by laeti-tia** [comment]
Also, need an owner change on `/var/log/pscheduler/pscheduler.log` which will be achieved thanks to https://github.com/perfsonar/pscheduler/commit/c5acd051a449ba04db4defb78dc9fbacb34b64df

**Comment by szymontrocha** [comment]
I tested with today's nightly built and it seems the fix is wokring. That's great:
```
$ ls -la pscheduler*
lrwxrwxrwx 1 perfsonar perfsonar 28 Mar 25 06:48 pscheduler.log -> ../pscheduler/pscheduler.log
$
```

**Comment by laeti-tia** [comment]
Thanks! Can you also make sure you can actually read it too?

**Comment by szymontrocha** [comment]
Yes, I can read it without sudo
