### ISSUE TITLE
firewall not set with fresh toolkit install on Debian10

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/toolkit#458]
I noticed that after fresh install of perfsonar-toolkit bundle under Debian 10.13 I don't have any perfsonar setting in firewall which I guess should open/block specific ports related to services:

```
root@psmall-poz1:~# firewall-cmd --list-all
Error: INVALID_ZONE
root@psmall-poz1:~# firewall-cmd --list-all --zone=public
public
  target: default
  icmp-block-inversion: no
  interfaces:
  sources:
  services:
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:

root@psmall-poz1:~# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
INPUT_direct  all  --  anywhere             anywhere
INPUT_ZONES_SOURCE  all  --  anywhere             anywhere
INPUT_ZONES  all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere             ctstate INVALID
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
FORWARD_direct  all  --  anywhere             anywhere
FORWARD_IN_ZONES_SOURCE  all  --  anywhere             anywhere
FORWARD_IN_ZONES  all  --  anywhere             anywhere
FORWARD_OUT_ZONES_SOURCE  all  --  anywhere             anywhere
FORWARD_OUT_ZONES  all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere             ctstate INVALID
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
OUTPUT_direct  all  --  anywhere             anywhere

Chain INPUT_direct (1 references)
target     prot opt source               destination

Chain INPUT_ZONES_SOURCE (1 references)
target     prot opt source               destination

Chain INPUT_ZONES (1 references)
target     prot opt source               destination
IN_public  all  --  anywhere             anywhere            [goto]

Chain FORWARD_direct (1 references)
target     prot opt source               destination

Chain FORWARD_IN_ZONES_SOURCE (1 references)
target     prot opt source               destination

Chain FORWARD_IN_ZONES (1 references)
target     prot opt source               destination
FWDI_public  all  --  anywhere             anywhere            [goto]

Chain FORWARD_OUT_ZONES_SOURCE (1 references)
target     prot opt source               destination

Chain FORWARD_OUT_ZONES (1 references)
target     prot opt source               destination
FWDO_public  all  --  anywhere             anywhere            [goto]

Chain OUTPUT_direct (1 references)
target     prot opt source               destination

Chain IN_public (1 references)
target     prot opt source               destination
IN_public_log  all  --  anywhere             anywhere
IN_public_deny  all  --  anywhere             anywhere
IN_public_allow  all  --  anywhere             anywhere
ACCEPT     icmp --  anywhere             anywhere

Chain IN_public_log (1 references)
target     prot opt source               destination

Chain IN_public_deny (1 references)
target     prot opt source               destination

Chain IN_public_allow (1 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh ctstate NEW,UNTRACKED

Chain FWDI_public (1 references)
target     prot opt source               destination
FWDI_public_log  all  --  anywhere             anywhere
FWDI_public_deny  all  --  anywhere             anywhere
FWDI_public_allow  all  --  anywhere             anywhere
ACCEPT     icmp --  anywhere             anywhere

Chain FWDI_public_log (1 references)
target     prot opt source               destination

Chain FWDI_public_deny (1 references)
target     prot opt source               destination

Chain FWDI_public_allow (1 references)
target     prot opt source               destination

Chain FWDO_public (1 references)
target     prot opt source               destination
FWDO_public_log  all  --  anywhere             anywhere
FWDO_public_deny  all  --  anywhere             anywhere
FWDO_public_allow  all  --  anywhere             anywhere

Chain FWDO_public_log (1 references)
target     prot opt source               destination

Chain FWDO_public_deny (1 references)
target     prot opt source               destination

Chain FWDO_public_allow (1 references)
target     prot opt source               destination
root@psmall-poz1:~# pscheduler troubleshoot
Performing basic troubleshooting of psmall-poz1.

psmall-poz1:

  Measuring MTU... 65535 (Local)
  Looking for pScheduler... OK.
  Fetching API level... 5
  Checking clock... OK.
  Exercising API... Archivers... Contexts... Tests... Tools... OK.
  Fetching service status... OK.
  Checking services... Ticker... Scheduler... Runner... Archiver... OK.
  Checking limits... OK.
  Idle test.... 5 seconds... Missed... Failed.

Did not get a result: Resource Not found.

root@psmall-poz1:/var/log#
```

**Comment by laeti-tia** [comment]
Might be related to #427

**Comment by laeti-tia** [comment]
@szymontrocha Can you check if enabling the `buster-backports` repository and installing `iptables` from it can have an effect on your issue?

This can be done by adding the following line in the `/etc/apt/sources.list`:
```
deb http://deb.debian.org/debian buster-backports main
```
and then installing the new version with:
```
apt-get install -t buster-backports iptables
```

And then rerun the perfSONAR script.

**Comment by laeti-tia** [comment]
That is indeed looking good.  I think we can just provide the updated iptables 1.8.5 package in our repository, copied from `buster-backports` so that users don't need to configure this repository themselves.  See https://github.com/perfsonar/minor-packages/commit/bdc32d73314e5db61b74fb2f919420eb0d4a2bef

**Comment by szymontrocha** [comment]
I used a fresh Debian 10 and added this apt sources file: https://perfsonar-repo.geant.org/debian/perfsonar-5.0-snapshot.list.
Then installed perfsonar-toolkit. Unfortunately it doesn't seem to set iptables rules. Even after running `apt-get reinstall perfsonar-toolkit-security` iptables are still empty
```
# iptables -V
iptables v1.8.2 (nf_tables)
```
`apt-get upgrade` writes:
The following packages heave been kept back:
 iptables

**Comment by laeti-tia** [comment]
Well, that seems more complicated than anticipated.  The new `iptables` version has [a lot of dependencies coming from the `buster-backports` repository](https://packages.debian.org/buster-backports/iptables) (see all packages ending in `~bpo10+` and then the dependencies to those packages) some of which might conflict with other things.  I overlooked that and I actually think it's not a good idea to provide all those additional packages in our own repository.

I'd suggest that instead we write a FAQ entry stating that if users want to make full use of the `perfsonar-toolkit-security` package on Debian 10, they'll need to activate the Debian 10 backports repository.

**Comment by mfeit-internet2** [comment]
> I'd suggest that instead we write a FAQ entry stating that if users want to make full use of the perfsonar-toolkit-security package on Debian 10, they'll need to activate the Debian 10 backports repository. 

Would it be worth making activating that repository a standard step in the installation just as we do for EPEL on Red Hat systems?

**Comment by laeti-tia** [comment]
> Would it be worth making activating that repository a standard step in the installation just as we do for EPEL on Red Hat systems?

I'm not sure it's needed as a general rule, but maybe.  This is the only case where that would help, but maybe we could benefit from newer versions of some other packages too.

**Comment by laeti-tia** [comment]
@szymontrocha Here is what I suggest to add to the FAQ:

The `perfsonar-toolkit-security` package, which configures the firewall for perfSONAR purposes, is not being set up properly under a plain Debian 10 installation.  This is due to an old iptables version provided with Debian 10.  Using the updated packages from Debian 10 backports solves this issue and properly configures the firewall.  To use this correction, you can follow the 3 simple steps described here:

1. Add the following line in the /etc/apt/sources.list:
```deb http://deb.debian.org/debian buster-backports main```

2. Then refresh apt and install the new version with:
```apt-get update; apt-get install -t buster-backports iptables```

3. And finally re-install the perfsonar package to make sure everything is setup properly:
```apt-get reinstall perfsonar-toolkit-security```

**Comment by szymontrocha** [comment]
I added a FAQ entry
