### ISSUE TITLE
Remove NPAD and NDT from web GUI if not installed

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#46]
We are dropping NPAD support in 3.5. For now we should probably only display npad if it is installed. I think this would be better than dropping it completely so people don't forget it's there who upgrade from previous versions, but could probably be swayed to dropping it entirely if that proves too cumbersome.

**Comment by apertome** [comment]
the get_services webservice needs to check whether npad is installed and not return npad info at all if it's not installed.

should we treat NDT this same way?

**Comment by arlake228** [comment]
Probably not a bad idea on NDT.

**Comment by sowmyab** [comment]
Added this feature  in  commit 5be355a18026d8063272670bddf49d03caedb18a

**Comment by apertome** [comment]
Looks good, closing
