### ISSUE TITLE
Country database update request

### ISSUE THREAD

**Issue by apcooper** [perfsonar/toolkit#460]
I'd like to suggest that the country database in the toolkit just use "Taiwan" to refer to Taiwan, rather than the current longer (and contentious) choice of words.

As a new user based in Taiwan, I came across this when entering admin information in the toolkit configuration.

I expect the background to the wider issue (ISO 3166 etc.) is now well-enough understood, so I don't think I need to give a detailed explanation, but please feel free to ask. Given that all options have some element of controversy, I suggest "Taiwan" is the most neutral. 

(For what it's worth, this is the choice of the likes of CERN and NERSC on their various web interfaces etc., and these days is the default expectation, IMO.)

Thanks for your attention.

**Comment by mfeit-internet2** [comment]
We understand the issue at hand, but this is, ultimately, a dispute between Taiwan and the ISO. The project holds no position on this and tends to follow standards when one exists. By deviating from ISO 3166, we would be taking a position.  If ISO changes the name, we'll update the list.
