### ISSUE TITLE
Plot-Schedule Graph menu option doesn't open due to permission error under Ubuntu

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/toolkit#468]
When I try to launch "Plot-Schedule Graph" from Configuration tab Tests under Resources right-hand menu I got an error and can't open this page (https://foo.bar/toolkit/admin/plot.cgi):

Forbidden
You don't have permission to access this resource.

I tried it in a couple of 5.0.8 toolkit hosts and it's the same behaviour everywhere. I found this error only in Ubuntu 20 hosts. I tried one with Cetos7.9 and it works there
I tried it in 5.1beta and it seems to work properly there too under Ubuntu 20

Szymon

**Comment by laeti-tia** [comment]
The new perfsonar-toolkit 5.0.8-2 should solve this issue.
