### ISSUE TITLE
more branding on new gui?

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#47]
Right now the new GUI doesn't have any perfSONAR logos or similar to distinguish it as such. We certainly don't want to plaster logos all over like it's NASCAR, but seems like a well placed crosshairs or two might be good for tying it back to the rest of the project. This is just a suggestion, I am not on the branding team that theoretically exists, just a thought that arose.

**Comment by apertome** [comment]
Good suggestion, I think I initially held back on logos since I didn't know if the branding team was going to come up with something -- I also think it could use a little more color perhaps, but I don't know whether there are official colors or not.

As far as I know, the branding team hasn't really determined a new logo or anything like that, you wouldn't happen to know, would you?

**Comment by apertome** [comment]
In fact, I was going to have someone here design a new logo several months ago, but I believe it was decided to wait for the branding effort for that.

**Comment by arlake228** [comment]
I was more thinking of the current green and black crosshairs logo which we use on the website, documentation, github, etc. I guess I didn't realize there was potential logo redesign efforts. I don't really mind the current logo but I am not on the branding team. Like I said, just something that jumped out at me when I saw the page.

**Comment by szymontrocha** [comment]
Who is in the branding team? Is there somebody from GEANT project team to support the work?

**Comment by apertome** [comment]
I haven't heard anything about that project in some time, so I'm not sure if anything is happening with it. @bltierney might know.

**Comment by apertome** [comment]
OK, we are sticking with the current logo right now. I will be adding it to the UI soon

**Comment by apertome** [comment]
A new edit of the logo (basically with inverted colors to work on the dark background) is being reviewed by the steering committee.

**Comment by apertome** [comment]
The logo has been in place for some time, with no complains. Closing.
