### ISSUE TITLE
Remove servicewatcher on upgraded hosts

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#470]
We noticed on Raul's host that got upgraded that psconfig was taken-out hourly be servicewatcher. we no longer ship servicewatcher, nor was it removed on update. Manually removing the RPM fixed things.

We should be able to some stuff with obsoletes in spec to get it removed....alternatively could run script to disable it....which would have advantage of working on RPM and DEB update.

**Comment by laeti-tia** [comment]
Breaks:/Replaces: implemented in Debian packages, to be tested.

**Comment by arlake228** [comment]
Added Obsoletes/Provides in RPM, to be tested.

**Comment by arlake228** [comment]
confirmed on debian and ubuntu.
