### ISSUE TITLE
Mismatch between #tests showed in GUI and psconfig output in 5.1

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/toolkit#471]
I noticed that the numbers shown in Toolkit gui under "Tests Configured by Type" is different from what psconfig says. Throughput test is counted less while I think both numbers should be equal.

In my test host:

CLI gives 10 tests:
`
$ psconfig pscheduler-tasks | jq 'map({dest: .test.spec.dest, type:.test.type})'
[
  {
    "dest": "psmall-poz1.man.poznan.pl",
    "type": "rtt"
  },
  {
    "dest": "150.254.160.18",
    "type": "latencybg"
  },
  {
    "dest": "psmall-poz1.man.poznan.pl",
    "type": "latencybg"
  },
  {
    "dest": "150.254.160.18",
    "type": "throughput"
  },
  {
    "dest": "psmall-poz1.man.poznan.pl",
    "type": "throughput"
  },
  {
    "dest": "perfsonar.eenet.ee",
    "type": "trace"
  },
  {
    "dest": "psmall-poz1.man.poznan.pl",
    "type": "trace"
  },
  {
    "dest": "perfsonar.eenet.ee",
    "type": "rtt"
  },
  {
    "dest": "150.254.160.18",
    "type": "latencybg"
  },
  {
    "dest": "perfsonar.eenet.ee",
    "type": "latencybg"
  }
]
`

while GUI shows 9 tests (throughput is just 1)
![obraz](https://github.com/perfsonar/toolkit/assets/12281679/7dd37ff0-adf4-4f52-b3b9-f3a1b58db9c3)

**Comment by arlake228** [comment]
I think this is maybe just a wording issue that is causing confusion. The counts on the dashboard come from the results in Opensearch for the timeframe selected in grafana. The numbers are correct in that respect, but looks like one of the throughput tests didn't have a result in that time window, so there is one less result. The heading says "Tests Configured" though and as you point out there is another throughput test "configured" even if it does not have a result.

I have changed the heading to be "Test Results by Type" which more accurately conveys what that table is showing.

**Comment by szymontrocha** [comment]
This is fine for me
