### ISSUE TITLE
Variable definition for annotations in Grafana template for building Host Metrics returns wrong value

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/toolkit#476]
"perfSONAR Host Metrics" dashboard template contains annotations to show throughput tests. I found that the template uses variable $node_name which is then used to construct the query for annotations.

The variable says: `{"find":"terms", "field":"meta.uname.nodename.keyword", "query": "meta.id: $host", "size": 1}`

And annotations reference them:
```
test.type.keyword: throughput AND meta.destination.hostname.keyword: ${node_name}
test.type.keyword: throughput AND meta.source.hostname.keyword: ${node_name}
```

However node_name variable returns short hostname instead of FQDN which is contained in the field  meta.destination.hostname.keyword or meta.source.hostname.keyword. Therefore the query doesn't work i.e. returns nothing.

So in my testing host with 5.1 toolkit under Ubuntu 20 variable value is retrieved as `psmall-poz2` while `meta.source.hostname.keyword` field returns FQDN `psmall-poz2.man.poznan.pl`

To match variable to the query in annotation I tested another field in annotation i.e. `reference.psconfig.created-by.agent-hostname: $node_name` which in my case returns short hostname but I'm not sure this is a valid solution.

```
root@psmall-poz2:/# hostname
psmall-poz2
root@psmall-poz2:/# host 150.254.160.18
18.160.254.150.in-addr.arpa domain name pointer psmall-poz2.man.poznan.pl.
root@psmall-poz2:/# 
```

**Comment by arlake228** [comment]
I corrected this to filter on the normalized ip fields in pscheduler records in addition to name. This was made possible by other issue reported that led to IP collection and seems to work better.
