### ISSUE TITLE
null displayed at top of new GUI page when no hostname

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#48]
The text "null" is displayed at the top of the page when there is no hostname (e.g. there is just an IP). It'd be nice if it displayed something else. It might also be nice if there was a way to override the default selection (maybe even not require it to be a hostname IP) since determining the primary address/hostname can be a tricky business when dealing with multiple interfaces.

**Comment by apertome** [comment]
Adding Sowmya since she is doing some other tasks involving interfaces

**Comment by sowmyab** [comment]
Added a config option to web_admin.conf. Can be found in commit 58e7cb89be7e7f7e2522394020245f40c123a815

**Comment by apertome** [comment]
Seems to be fixed, would like to test on a live host with this problem.
