### ISSUE TITLE
/serviceTest/psGraph.cgi says "Loading" indefinitely

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#51]
When using the old interface, /serviceTest/psGraph.cgi spins indefinitely. Everything works fine on the new interface. May just be a toolkit deployment issue, so put it here instead of graphs project/ 
![ps-3 5rc1-results-loading](https://cloud.githubusercontent.com/assets/634851/8581129/c6f3cdac-258c-11e5-9b4c-32e7c3a6869d.PNG)

**Comment by apertome** [comment]
Has the serviceTest/graphs package been updated alongside the 3.5rc1 release?

**Comment by apertome** [comment]
I see the issue, a template file didn't get updated
