### ISSUE TITLE
New GUI missing primary interface and MTU

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#52]
It was noted on the USATLAS call that the Primary Interface and MTU were often missing on the New GUI. See http://nettest.lbl.gov/toolkit-ng/. It may or may not be related to hosts not having an eth0 (e.g. nettest has an eth2).

**Comment by apertome** [comment]
Sowmya is already looking into some things involving the interfaces, maybe she can check this as well

**Comment by sowmyab** [comment]
The issue was if a primary interface was specified in web_admin.conf and if that interface was not up, then discover_external_address did not attempt to find other interfaces. This has been fixed in commit 0d3c0bd8cb4c501b705c99cd542a9db179bdb9ae

**Comment by apertome** [comment]
Sowmya's commit seems to fix this as far as I can tell; however, I don't have a host that was exhibiting this behavior. Andy, is there a way to test this somewhere?

**Comment by apertome** [comment]
We have not received any more reports of this bug. Closing.
