### ISSUE TITLE
Ask about changing ntp.conf when perfsonar-toolkit-ntp is installed

### ISSUE THREAD

**Issue by tonin** [perfsonar/toolkit#57]
The Debian package perfsonar-toolkit-ntp contains a suggestion of NTP servers to use and the enclosed script `autoselect_ntp_servers` should choose the closest ones.

When this package is being installed, it should ask the user if the system's `/etc/ntp.conf` file should get replaced by the output of this script.

**Comment by arlake228** [comment]
I actually disagree with this. The Toolkit by definition messes with a lot of system configuration , not just NTP. If you don't want files like this touched, don't install the Toolkit package and use of our other bundles or a custom set. We have split out the NTP stuff to it's own package so if someone wants to avoid the NTP stuff altogether they have a means to do so. Prompting for stuff like this is a slippery slope and we'll be deluging people with prompts.

**Comment by tonin** [comment]
Ok, so you're suggesting that when `perfsonar-toolkit-ntp` package is installed, it changes `/etc/ntp.conf` right away with the closes NTP servers returned by the autoselect script.

Brian was suggesting to ask the administrator a question, but I'm not sure if the question would be to suggest the installation of the `perfsonar-toolkit-ntp` package or to ask if `/etc/ntp.conf` should be changed.

At the moment, for Debian installations, this package is not part of any bundle so it doesn't get installed automatically, but the administrator can install it on top of any other bundle.  We can just keep it that way and just document that behaviour.

**Comment by arlake228** [comment]
Yes, I am suggesting we keep it as is and have it replace ntp.conf on initial install and document the default behavior (which we already do on http://docs.perfsonar.net/manage_ntp.html). I am open to further updating the docs as well. 

Also as a general note, adding prompts to an RPM (and I am guessing a Debain package as well) is considered poor form. Also,  it would completely break the ISO install since that method has no way to grab the user input.

**Comment by bltierney** [comment]
I think there are 3 use cases to consider here:

1) individual install of perfsonar-toolkit-ntp
2) perfsonar-toolkit-ntp gets installed as part of perfsonar-testpoint
3) perfsonar-toolkit-ntp gets installed as part of perfsonar-toolkit

I think for #3, ntp.conf should get replaced by default.
I think for #1 and 2, it should prompt before overwriting ntp.conf.

Is this possible?

**Comment by bltierney** [comment]
I discussed this with Andy more, and we decided to leave the package as is, and document what needs to be done.

For example, this page:

http://docs.perfsonar.net/3.5rc1/install_debian

We should add something like:

You may also want to install package perfsonar-toolkit-ntp if you are not managing your ntp.conf file in some other manner.

**Comment by apertome** [comment]
Can we close this?

**Comment by bltierney** [comment]
I think we can. Andy?

**Comment by arlake228** [comment]
Yep, looks like docs were updated.
