### ISSUE TITLE
Warning: cassandra20-2.0.14-1.noarch.rpm is not signed

### ISSUE THREAD

**Issue by igarny** [perfsonar/toolkit#59]
Hi,

Here is the output of the install attempt

Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install perl-perfSONAR_PS-Toolkit' returned 1:

Package cassandra20-2.0.14-1.noarch.rpm is not signed

we are using this KEY: http://software.internet2.edu/rpms/RPM-GPG-KEY-Internet2

Best regards,
Ivan

**Comment by arlake228** [comment]
Can you send the full output of "yum install cassandra20"? I'm curious what mirror and repo you are using since it appears to be signed in the Internet2 repo.

**Comment by apertome** [comment]
I'm guessing this has been addressed?

**Comment by arlake228** [comment]
Have not been able to reproduce for many months so closing.
