### ISSUE TITLE
Update Regular Testing GUI to use new LS caching service

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#6]
_From @arlake228 on March 14, 2015 11:34_

Original [issue 753](https://code.google.com/p/perfsonar-ps/issues/detail?id=753) created by arlake228 on 2013-08-09T13:57:14.000Z:

Currently we have two major things that rely on the CSV files we refer to as the &quot;index&quot; service: the global services page and the regular testing GUI. Andrew is currently working on a replacement for the Global Services GUI, but for regular testing we need to make some changes. I think the right thing to do for this is to use Sowmya's new caching service that subscribes to the main LSes and just grabs bwctl, owamp, ping and traceroute services. We can ignore MAs, their tests, host, interfaces etc so its not a full LS dump. The GUI can likely just do a live query in this case (or live-ish, maybe you'll have a client side cache but expire it after a minute or two). Not a top priority now, just making a note so we don't forget

_Copied from original issue: perfsonar/project#752_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=753#c1) originally posted by arlake228 on 2013-10-18T18:04:32.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=753#c2) originally posted by arlake228 on 2013-10-30T03:35:10.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Comment [#3](https://code.google.com/p/perfsonar-ps/issues/detail?id=753#c3) originally posted by arlake228 on 2014-05-06T17:56:02.000Z:

Issue 743 has been merged into this issue.

**Comment by arlake228** [comment]
Comment [#4](https://code.google.com/p/perfsonar-ps/issues/detail?id=753#c4) originally posted by arlake228 on 2014-08-22T13:27:37.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Comment [#5](https://code.google.com/p/perfsonar-ps/issues/detail?id=753#c5) originally posted by arlake228 on 2015-01-27T14:38:04.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
is this still possible by 3.5 or will we be moving it to 3.6?

**Comment by sowmyab** [comment]
Hi Andy,

We decided to move this to 3.6 at the beginning of 3.5 release planning
process. The spreadsheet reflects this but I forgot to update it here.

Thanks,
Sowmya

**Comment by arlake228** [comment]
That's what i thought I remembered. Milestone updated, thanks.

**Comment by arlake228** [comment]
Duplicates perfsonar/project#1122
