### ISSUE TITLE
remove logscraper script from default install

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#61]
The logscraper script uses a lot of system resources on busy hosts and has affected some the WLCG hosts ability to complete tests in a few cases because it eats all the CPU. Since we don't display it in the new GUI is probably makes sense to remove the cron job by default. We can add instructions on how to reinstall it (copy it to cron.hourly) as an option for anyone if they really miss it and want to look at the old web interface.

**Comment by apertome** [comment]
I'll be curious to see if anyone misses those log analysis pages. If we get a lot of complaints that they're missing, we may need to integrate them into the new GUI.

**Comment by arlake228** [comment]
agreed
