### ISSUE TITLE
Problem loading graphs from Chrome on Windows 

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#63]
A user reported that on the main page of a 3.5 host, if you click on a graph, close it, then open another graph that the graph won't load. This only happens on Windows Chrome and not on Mac Chrome. I was on a call where multiple people were able to verify both of these things.

**Comment by apertome** [comment]
Very strange, I will see if I can reproduce this one at home, since I have a Windows box there.

**Comment by apertome** [comment]
I've got a Windows 10 VM running the latest Chrome now and so far I can't reproduce this. I'll keep trying. 

Can you/they provide more details? were they looking at the authenticated dashboard, or public? What version of Windows/Chrome?

**Comment by apertome** [comment]
Ivan reported this issue as well, although he's seeing multiple graphs; the first ones that he views are not going away and new ones are added.

**Comment by igarny** [comment]
Hi guys,

I am observing this misbehavior on Windows with IE 11, FF 42.0, GC 48.0

Best regards,
Ivan
![ps-gui-2graph-sel-ie](https://cloud.githubusercontent.com/assets/11942774/11624657/8c4b040c-9cd5-11e5-8910-b43e963fa847.jpg)
![ps-gui-2graph-sel-ff](https://cloud.githubusercontent.com/assets/11942774/11624658/8c5515d2-9cd5-11e5-95c5-634723278afa.jpg)

**Comment by apertome** [comment]
Ivan,

Thanks for providing the screenshots. They clarify a lot. It looks like this is a separate bug from what I was thinking.

**Comment by apertome** [comment]
I just tried and I can't reproduce the behavior. Can you describe what you were doing when this happened?

I was looking at this example, which appears to be in the same mesh you were looking at, I believe:
http://ps-dashboard.es.net/details.cgi?uri=/maddash/grids/ESnet+-+ESnet+to+GEANT+Packet+Loss+Testing/psmp-gn-owd-01.ams.nl.geant.net/aofa-owamp.es.net/Loss+Reverse

**Comment by igarny** [comment]
Man things changed! I cannot reproduce that either.
I have tried Firefox and Chrome and it works perfectly.
Now it is only my old IE that can see this, but I am not fond of this browser anyway.

**Comment by igarny** [comment]
Sorry I pushed the wrong button and closed it....

**Comment by apertome** [comment]
So far I haven't reproduced this, but I will try again before the 3.5.1 release.

**Comment by apertome** [comment]
Can't reproduce (and Ivan said neither could he at the last meeting). Closing.
