### ISSUE TITLE
Web Interface shows strange values for swap space

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#64]
A user reported that they were seeing strange values for swap space on their toolkit host. It worked on one of their hosts but they saw a value in Zetabytes on on another. The host in question is psmsu06.aglt2.org though I believe you need admin access to see it.

**Comment by apertome** [comment]
Do you think it would be possible to get the output of this?
https://psmsu06.aglt2.org/toolkit/services/host.cgi?method=get_health

especially swap_used and swap_total, but may help to see all of it

**Comment by arlake228** [comment]
{"swap_used":1.88894659314781e+22,"mem_used":3572985856,"mem_total":4015947776,"rootfs":{"used":6840025088,"total":241320099840},"swap_total":4227854336,"cpu_util":"2.48","load_avg":{"avg_15":"0.17","avg_5":"0.12","avg_1":"0.11"}}

**Comment by arlake228** [comment]
here is the output of free too for comparison:

free -m
             total       used       free     shared    buffers     cached
Mem:          3829       3353        476          2        229       1115
-/+ buffers/cache:       2007       1822 
Swap:         4031 1759218604       4519

**Comment by apertome** [comment]
Why is their reported used swap vastly larger than the total swap? Free swap is also showing greater than total swap. Something seems wrong in their environment, no?

**Comment by apertome** [comment]
Can you do 
df -Th
if you get a chance?

**Comment by apertome** [comment]
One of our systems guys suggests
hmm, 4GB of swap, and ~3GB of ram, i386 system without PAE?

**Comment by apertome** [comment]
the LS says x86_64
http://stats.es.net/ServicesDirectory/#search=psmsu06&uri=lookup%2Fservice%2F9ea06f66-d915-439d-a57a-04ca29576598

Kernel: Linux 2.6.32-573.3.1.el6.web100.x86_64

(assuming that's accurate)

**Comment by arlake228** [comment]
[root@psmsu06 ~]# df -Th
Filesystem           Type   Size  Used Avail Use% Mounted on
/dev/mapper/VolGroup-lv_root
                     ext4   225G  6.5G  207G   4% /
tmpfs                tmpfs  1.9G     0  1.9G   0% /dev/shm
/dev/sda1            ext4   477M   96M  356M  22% /boot

**Comment by arlake228** [comment]
chalked up to host issue.
