### ISSUE TITLE
Improve scalability of test listing

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#70]
From a user:

Finally, one observation from the new UI, at least in Chrome when I load the toolkit homepage, the loading bar disappears (if I click on the page), but there are no tests shown, sometimes it takes couple of minutes to load them (sometimes they don’t appear at all). It would be good to add an indication if the loading processing is still going on or has stopped since right now it’s quite confusing, one is expected to wait but have no indication of any progress (I would suggest an integrated progress bar, instead of just loading bar). This is for sure due to the large number of tests we’re doing (check e.g. http://psum01.aglt2.org/toolkit/)

**Comment by apertome** [comment]
In general, we need to make the test listing scale better.

**Comment by apertome** [comment]
This is mostly an issue for 3.6, but we should see if we can make some improvements in 3.5.1.

**Comment by apertome** [comment]
This is much improved, it now displays the test results in a more "progressive" manner, first fetching the list of tests, displaying it, and then trying to fill in the data if possible. On one very busy host, it used to take around 30-60 seconds to display anything (sometimes timing out); now it takes about 8 seconds for the table to display. An error is displayed if it times out.

The loading indicators give users a much better sense of what's going on.

These changes will also enable us to do some pagination, but that will be an issue for 3.6.

**Comment by apertome** [comment]
Closing for now. Opened a new issue to track this for 3.6, see #89.
