### ISSUE TITLE
non local css files

### ISSUE THREAD

**Issue by daldoyle** [perfsonar/toolkit#76]
This was noticed by zoumlander@hotmail.com on the users list.

The following two resources in "/opt/perfsonar_ps/toolkit/web-ng/templates/components/top.html" are being pulled down remotely. This can create problems when people do installs of the toolkit in places that do not have access to the general internet. We should grab these files and store them locally in the toolkit and reference the local versions.

GET http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css
GET https://fonts.googleapis.com/css

**Comment by apertome** [comment]
Planning on addressing this in the near future

**Comment by apertome** [comment]
It was a little more complicated than expected, but I went ahead and added these
