### ISSUE TITLE
pS Documentation Not on Node

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/toolkit#77]
The documentation for the toolkit should be shipped with it and served up by the node's web server instead of requiring a trip out to the Internet to get at it.

**Comment by arlake228** [comment]
I don't know that I agree with this. It's a good way to have old copes of the documentation out in the world and have people quoting. Half the physical products I buy nowadays don't come with instruction manuals and expect me go to their website, let alone digital ones. I think having it remote is the preferred way to do it in my opinion.

**Comment by mfeit-internet2** [comment]
Getting it remotely works until what's on the web is no longer the same version as what's on the node; then you get support calls where the docs say it should zig and the user sees it zag.  If the docs are part of the software, it's always the correct thing.  I bumped into that during the 3.4/3.5 transition.

Without it, users on networks with no Internet access are out of luck.

Anyway, it's a good topic for discussion, and this is just a flag in the sand.

**Comment by arlake228** [comment]
Not out of luck in that case, see http://docs.perfsonar.net/previous_releases.html

**Comment by bltierney** [comment]
closing this. Any objections?
