### ISSUE TITLE
UDP test bandwidth not honoring the Mbps label

### ISSUE THREAD

**Issue by tonin** [perfsonar/toolkit#78]
The UDP test configuration dialog is labelling the UDP Bandwidth parameter as being in Mbps and stores the value as is in the `regular_testing.conf` file.  However, the regular_testing daemon, bwctl and iperf are interpreting that to be in bps.  Ref: http://docs.perfsonar.net/config_regular_testing.html#udp-bandwidth-directive

We should either add the `M` suffix to the value stored in the `regular_testing.conf` file so it gets interpreted correctly by iperf, or remove the Mbps label in the GUI.

**Comment by apertome** [comment]
Thanks Antoine, we'll want to fix this one soon.
