### ISSUE TITLE
Updating Admin Info and hitting save gives wrong prompt

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#80]
A user reported the following:

> First -- and I am sorry this is only anecdotal but -- the web UI
seemed a little buggy...
>
>- On one of our four MSU+UM production nodes only:
I am pretty sure that I did not bump anything else than
the "save" button and I got a pop-up saying "are you sure
you want to leave this page"... which didn't make sense.
>
>- The whole experience was a bit confusing, but I am pretty sure
that I had to add communities repeatedly and only a subset
would stick until I reached the full set I wanted.
>
>- This could all be a confusion on my part and I wish I had been
more alert and went to look at the config files each time...
So you should use this as background information if you hear
other complaints.

I was able to recreate the problem by visiting the admin info page, changing a community and hitting save. The pop-up asked me if i wanted to leave the page, if I did nothing was saved. If I stayed on the page and hit save a second time, then it saved correctly. In my case it was on Mac Safari, not sure about the user's browser.

**Comment by apertome** [comment]
This may already be resolved, as I've changed quite a bit about how the communities are saved, but I'll do some more testing to be sure.

**Comment by apertome** [comment]
With the recent changes to this page, this issue is resolved.
