### ISSUE TITLE
Default to always make a traceroute test with the scheduling of any Latency/BW test

### ISSUE THREAD

**Issue by JWZurawski** [perfsonar/toolkit#83]
Having traveroute data 'always' (not just when someone specifically sets of the test) would be valuable.  I propose a new policy - when one schedules any test (ping, OWD, throughput) it is understood that a traceroute test gets kicked off as well.  Perhaps there could be a checkbox in the GUI that can be unchecked if they really don't want this behavior.

**Comment by arlake228** [comment]
How is this different than what we already do? If someone creates a throughput or OWAMP test through the GUI it creates a traceroute test.



On January 13, 2016 at 10:47:30 AM, Jason Zurawski (notifications@github.com) wrote:

Having traveroute data 'always' (not just when someone specifically sets of the test) would be valuable. I propose a new policy - when one schedules any test (ping, OWD, throughput) it is understood that a traceroute test gets kicked off as well. Perhaps there could be a checkbox in the GUI that can be unchecked if they really don't want this behavior.

**Comment by arlake228** [comment]
Chatted with Jason and ran some local tests with the GUI to confirm it behaves in the desired way. It appears to do what it is supposed to, so closing.
