### ISSUE TITLE
Update links to perl-shared repository or package differently?

### ISSUE THREAD

**Issue by tonin** [perfsonar/toolkit#86]
Reviewing the perfSONAR perl library packaging, I'm wondering if those modules shouldn't be moved out of the toolkit repo to the perl-shared repo:

https://github.com/perfsonar/toolkit/blob/master/lib/perfSONAR_PS/Client/gLS/Keywords.pm
https://github.com/perfsonar/toolkit/blob/master/lib/perfSONAR_PS/Utils/Closest.pm
https://github.com/perfsonar/toolkit/tree/master/lib/perfSONAR_PS/Utils/Config

Or the other files the other way around?  Actually Aaron had done that more than a year ago: https://github.com/perfsonar/toolkit/commit/d4d771889ae5a510b30521964e2b9048718cd503?diff=unified

I'm not sure what is the reasoning, but shouldn't we review that as part of the package cleanup task?

**Comment by aaronmbr** [comment]
I moved them out because nothing outside of the toolkit used them. The goal was to minimize the amount of junk in the shared library.

Cheers,
Aaron

**Comment by tonin** [comment]
Hi Andy, I guess this has been solved as part of your latest perl-shared repackaging.

**Comment by arlake228** [comment]
Agreed, marking as closed.
