### ISSUE TITLE
Further improve scalability of test listing and other improvements

### ISSUE THREAD

**Issue by apertome** [perfsonar/toolkit#89]
We need to add pagination to the test listing and make further performance improvements. This is a continuation of #70.

**Comment by apertome** [comment]
We also need to add a dropdown with a list of timeranges for people to choose, and somehow indicate that if they choose a large value, their host may not be able to handle it. The options should be something like:

- 1 hour
- 1 day
- 1 week (default)
- 2 weeks
- 3 weeks
- 1 month
- custom range(?)
- 1 year(?) - this may not even be feasible

We may want to cross-reference this list with the one on the graphs themselves and try to keep them consistent. In fact, that UI will be using a calendar widget, we might be able to use that here.

**Comment by apertome** [comment]
Assigning Lisa. Relates to #94. We may only do a subset of the above options, for simplicity's sake:

1 hour
1 day
1 week (default)
2 weeks
3 weeks
1 month

**Comment by apertome** [comment]
As far as adding pagination goes, we may want to use a new table widget. I had one in mind, I'll have to review my notes to find out which one it was.

**Comment by lisaens** [comment]
Made the table into a jquery DataTables widget, which adds pagination, sorting, and searching. Made changes to only get results that are showing and save them so that they don't have to be re-gotten if the user pages back and forth, etc.
