### ISSUE TITLE
Information regarding 'time window' used to calculate throughput/latency averages under 'test results'

### ISSUE THREAD

**Issue by JWZurawski** [perfsonar/toolkit#94]
This is a 2 for one request:

1) On the 'test results' page for each of the tests, it would be good to have a mouse over or pop-up that people can use to know long of a time window goes into calculating that number (e.g. if they are expecting it to change 'fast' they may be disapointed that its a pretty large time window)

2) Should the throughput be a month?  A week may be more sufficient.

**Comment by apertome** [comment]
The problem with the "window" is it's different for each test type. We'll figure out a way.

I want to add a dropdown selector for the timerange. Lisa can do this one.

**Comment by apertome** [comment]
This is related to #89

**Comment by apertome** [comment]
Actually reviewing this, they're dupes. Closing this one since most of the work is going on in #89. Also this is basically done and will appear in 3.6.
